window.NEWS_DATA = [
  {
    "id": 1,
    "category": "肿瘤",
    "date": "2026年7月14日",
    "month": "2026-07",
    "product": "EFGR",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "迪哲医药",
    "licensee": "阿斯利康",
    "source": "https://stockmc.xueqiu.com/202607/688192_20260714_LOKU.pdf"
  },
  {
    "id": 2,
    "category": "肿瘤",
    "date": "2026年7月2日",
    "month": "2026-07",
    "product": "未透露",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "英矽智能",
    "licensee": "武田制药",
    "source": "https://xueqiu.com/S/03696/397968666"
  },
  {
    "id": 3,
    "category": "肿瘤",
    "date": "2026年6月30日",
    "month": "2026-06",
    "product": "未透露",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "剂泰科技",
    "licensee": "Boulevard Bio",
    "source": "https://www.metispharma.com/qyxw/276.html"
  },
  {
    "id": 4,
    "category": "肿瘤",
    "date": "2026年5月29日",
    "month": "2026-05",
    "product": "未透露",
    "productType": "未透露",
    "diseaseType": "",
    "licenser": "信达生物",
    "licensee": "辉瑞",
    "source": "https://www.stcn.com/article/detail/3935413.html"
  },
  {
    "id": 5,
    "category": "肿瘤",
    "date": "2026年5月12日",
    "month": "2026-05",
    "product": "未透露",
    "productType": "未披露",
    "diseaseType": "",
    "licenser": "恒瑞医药",
    "licensee": "BMS",
    "source": "https://www.drugtimes.cn/2026/05/12/152yimeiyuanhengruiyubmsdachenghezuo/"
  },
  {
    "id": 6,
    "category": "肿瘤",
    "date": "2026年2月8日",
    "month": "2026-02",
    "product": "未透露",
    "productType": "未披露",
    "diseaseType": "",
    "licenser": "信达生物",
    "licensee": "礼来",
    "source": "https://baijiahao.baidu.com/s?id=1856650270575785195&wfr=spider&for=pc"
  },
  {
    "id": 7,
    "category": "肿瘤",
    "date": "2026年1月12日",
    "month": "2026-01",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "荣昌生物",
    "licensee": "艾伯维",
    "source": "https://www.cnpharm.com/upload/resources/file/2026/01/15/183282.pdf"
  },
  {
    "id": 8,
    "category": "肿瘤",
    "date": "2025年12月19日",
    "month": "2025-12",
    "product": "LRRC15",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "先声",
    "licensee": "益普生",
    "source": "https://www.simcere.com/news/detail.aspx?mtt=1556"
  },
  {
    "id": 9,
    "category": "肿瘤",
    "date": "2025年12月17日",
    "month": "2025-12",
    "product": "未透露",
    "productType": "多抗",
    "diseaseType": "",
    "licenser": "和铂医药",
    "licensee": "BMS",
    "source": "https://www.cn-healthcare.com/articlewm/20251218/content-1663027.html"
  },
  {
    "id": 10,
    "category": "肿瘤",
    "date": "2025年12月16日",
    "month": "2025-12",
    "product": "EGFR",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "翰森制药",
    "licensee": "Glenmark",
    "source": "https://cn.hspharm.com/news/news-detail-513401.htm"
  },
  {
    "id": 11,
    "category": "肿瘤",
    "date": "2025年8月29日",
    "month": "2025-08",
    "product": "未透露",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "科弈药业",
    "licensee": "Radiance Biopharma",
    "source": "https://finance.sina.cn/2025-09-04/detail-infpirxf1686981.d.html"
  },
  {
    "id": 12,
    "category": "肿瘤",
    "date": "2025年8月1日",
    "month": "2025-08",
    "product": "未透露",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "乐普生物",
    "licensee": "艾科联",
    "source": "https://mp.weixin.qq.com/s?__biz=Mzg3OTc3NjczMw==&mid=2247510833&idx=1&sn=377c6913ee70874923eb6a063134812e&poc_token=HIZqjWijufkhfRE6SX3XBrwU-LOlkvzvb_b-R6QQ"
  },
  {
    "id": 13,
    "category": "肿瘤",
    "date": "2025年6月26日",
    "month": "2025-06",
    "product": "GCSF",
    "productType": "融合蛋白",
    "diseaseType": "",
    "licenser": "迈威",
    "licensee": "齐鲁",
    "source": "https://stockmc.xueqiu.com/202506/688062_20250627_FLJL.pdf"
  },
  {
    "id": 14,
    "category": "肿瘤",
    "date": "2025年6月16日",
    "month": "2025-06",
    "product": "CDH6",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "先声再明",
    "licensee": "Nextcure",
    "source": "https://mp.weixin.qq.com/s/yXggs3-bMJUIEo9KiK05Cw"
  },
  {
    "id": 15,
    "category": "肿瘤",
    "date": "2025年6月5日",
    "month": "2025-06",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "智翔金泰",
    "licensee": "Cullinan",
    "source": "https://mp.weixin.qq.com/s/6Q5c1ugE72Z85d8jUzSRQQ"
  },
  {
    "id": 16,
    "category": "肿瘤",
    "date": "2025年6月2日",
    "month": "2025-06",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "BioNtech",
    "licensee": "BMS",
    "source": "https://mp.weixin.qq.com/s/peWaO6AbNss4jsgUIFeEmQ"
  },
  {
    "id": 17,
    "category": "肿瘤",
    "date": "2025年5月30日",
    "month": "2025-05",
    "product": "CLDN18.2",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "信诺威",
    "licensee": "安斯泰来",
    "source": "https://mp.weixin.qq.com/s/ai1aG32GEmBA2Hj1_5Ol4g"
  },
  {
    "id": 18,
    "category": "肿瘤",
    "date": "2025年5月20日",
    "month": "2025-05",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "三生制药",
    "licensee": "辉瑞",
    "source": "https://www.3sbio.com/news/details.aspx?id=307"
  },
  {
    "id": 19,
    "category": "肿瘤",
    "date": "2025年2月19日",
    "month": "2025-02",
    "product": "ROR1",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "石药",
    "licensee": "Radiance Biopharma",
    "source": "https://mp.weixin.qq.com/s/10DlZe9K5KExvweZARpFuw"
  },
  {
    "id": 20,
    "category": "肿瘤",
    "date": "2025年1月22日",
    "month": "2025-01",
    "product": "CDH17",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "乐普生物",
    "licensee": "ArriVent Biopharma",
    "source": "https://www.lepubiopharma.com/new/216.html"
  },
  {
    "id": 21,
    "category": "肿瘤",
    "date": "2025年1月13日",
    "month": "2025-01",
    "product": "GPRC5D/BCMA/CD3)",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "先声再明",
    "licensee": "Abbvie",
    "source": "https://www.simcere.com/news/detail.aspx?mtt=1485"
  },
  {
    "id": 22,
    "category": "肿瘤",
    "date": "2025年1月8日",
    "month": "2025-01",
    "product": "EGFR/HER3",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "映恩生物",
    "licensee": "Avenzo",
    "source": "https://mp.weixin.qq.com/s/dwruRrwz4bLVfF_lOli-Dg"
  },
  {
    "id": 23,
    "category": "肿瘤",
    "date": "2025年1月2日",
    "month": "2025-01",
    "product": "DLL3",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "信达生物",
    "licensee": "罗氏",
    "source": "https://mp.weixin.qq.com/s/jEdc_W_Pqkcl9erIdk-kFQ"
  },
  {
    "id": 24,
    "category": "肿瘤",
    "date": "2024年12月29日",
    "month": "2024-12",
    "product": "DLL3",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "恒瑞",
    "licensee": "IDEAYA",
    "source": "https://mp.weixin.qq.com/s/KaqNt4gtAiYcA0LKl24_sw"
  },
  {
    "id": 25,
    "category": "肿瘤",
    "date": "2024年12月4日",
    "month": "2024-12",
    "product": "未透露",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "映恩生物",
    "licensee": "GSK",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1733303268&ver=5668&signature=bHt7tKfzKB5kSTn3cy4Cnmmyzk1bv*6ew8Hcgu5E8jwbKnnUdqXp6urtvPwcXOpOIq-UCU0eBHbOBFPvI6*DRLV6-7ZlfGdA6HMoI4jmq3SHEorrXYQTcK2fPYCKWym5&new=1"
  },
  {
    "id": 26,
    "category": "肿瘤",
    "date": "2024年11月18日",
    "month": "2024-11",
    "product": "TROP2/NECTIN4",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "橙帆医药",
    "licensee": "Avenzo",
    "source": "https://mp.weixin.qq.com/s/XjkYoCEeG7k1r6pNerZMlw https://mp.weixin.qq.com/s/tP7di-D-VS_2NwatpbE4ww\nhttps://mp.weixin.qq.com/s?src=11&timestamp=1733492444&ver=5672&signature=26M3E7w6a8KE0wBWvsSoAXc1tHjwtg7MFJgh-buFxcco8CAS29622cZB8H5q*wNTV2q2Gxlyj7qL*ItfRDEmP9HPIW5XIQCp4ZteynYjhSv1eRcS8T8F3d7L*F2ITfM1&new=1"
  },
  {
    "id": 27,
    "category": "肿瘤",
    "date": "2024年11月17日",
    "month": "2024-11",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "康诺亚",
    "licensee": "Platina",
    "source": "https://staticpacific.blob.core.windows.net/press-releases-attachments/3504798/HKEX-EPS_20241117_11442884_0.PDF"
  },
  {
    "id": 28,
    "category": "肿瘤",
    "date": "2024年11月14日",
    "month": "2024-11",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "礼新",
    "licensee": "默沙东",
    "source": "https://www.msdchina.com.cn/2024/11/14/company_news_2024-11-14/"
  },
  {
    "id": 29,
    "category": "肿瘤",
    "date": "2024年11月13日",
    "month": "2024-11",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "普米斯",
    "licensee": "BioNTech SE",
    "source": "https://www.sec.gov/Archives/edgar/data/1776985/000177698524000094/a99_1biontechtoacquirebiot.htmhttps://cn.biotheus.com/news/344.html"
  },
  {
    "id": 30,
    "category": "肿瘤",
    "date": "2024年9月4日",
    "month": "2024-09",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "岸迈生物",
    "licensee": "Vignette",
    "source": "https://www.epimab.com/cn/news/41"
  },
  {
    "id": 31,
    "category": "肿瘤",
    "date": "2024年8月30日",
    "month": "2024-08",
    "product": "KRAS",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "加科思",
    "licensee": "艾力斯",
    "source": "https://www.allist.com.cn/newsd/101/2086.html"
  },
  {
    "id": 32,
    "category": "肿瘤",
    "date": "2024年8月19日",
    "month": "2024-08",
    "product": "未透露",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "科伦博泰",
    "licensee": "默沙东",
    "source": ""
  },
  {
    "id": 33,
    "category": "肿瘤",
    "date": "2024年8月9日",
    "month": "2024-08",
    "product": "CD3/CD19",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "同润生物",
    "licensee": "默沙东",
    "source": "https://www.msdchina.com.cn/2024/08/09/company_news/"
  },
  {
    "id": 34,
    "category": "肿瘤",
    "date": "2024年8月5日",
    "month": "2024-08",
    "product": "CD3/CD20",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "嘉和生物",
    "licensee": "TRC2004",
    "source": "https://www.genorbio.com/cn/media/corporate-news/20240805/"
  },
  {
    "id": 35,
    "category": "肿瘤",
    "date": "2024年8月1日",
    "month": "2024-08",
    "product": "PD-L1/VEGF和CTLA-4",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "宜明昂科",
    "licensee": "SynBioTx",
    "source": "https://www.sec.gov/Archives/edgar/data/1789769/000178976924000077/til-20240801.htm  http://www.immuneonco.com/news/gsdynamics/583.html"
  },
  {
    "id": 36,
    "category": "肿瘤",
    "date": "2024年6月18日",
    "month": "2024-06",
    "product": "PTK7",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "麦科思/普众",
    "licensee": "Day One",
    "source": "https://news.qq.com/rain/a/20240619A06J5O00"
  },
  {
    "id": 37,
    "category": "肿瘤",
    "date": "2023年12月28日",
    "month": "2023-12",
    "product": "PD-L1/SIRPα",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "科望医药",
    "licensee": "安斯泰来",
    "source": "https://www.astellas.com/en/news/28816"
  },
  {
    "id": 38,
    "category": "肿瘤",
    "date": "2023年12月12日",
    "month": "2023-12",
    "product": "EGFR/HER3",
    "productType": "ADC",
    "diseaseType": "",
    "licenser": "百利天恒",
    "licensee": "BMS",
    "source": "http://www.baili-pharm.com/upload/2023-12-12/128238727.pdf"
  },
  {
    "id": 39,
    "category": "肿瘤",
    "date": "2023年11月6日",
    "month": "2023-11",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "普米斯",
    "licensee": "BioNTech SE",
    "source": "https://cn.biotheus.com/news/333.html"
  },
  {
    "id": 40,
    "category": "肿瘤",
    "date": "2023年1月5日",
    "month": "2023-01",
    "product": "未透露",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "药明生物",
    "licensee": "GSK",
    "source": "https://www.wuxibiologics.com.cn/wuxi-biologics-and-gsk-enter-into-license-agreement-on-multiple-novel-bi-multi-specific-t-cell-engagers/"
  },
  {
    "id": 41,
    "category": "肿瘤",
    "date": "2022年12月6日",
    "month": "2022-12",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "康方生物",
    "licensee": "Summit",
    "source": "https://www.akesobio.com/cn/media/akeso-news/20221206/"
  },
  {
    "id": 42,
    "category": "肿瘤",
    "date": "2022年4月7日",
    "month": "2022-04",
    "product": "CD3/CLDN18.2",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "和铂医药",
    "licensee": "阿斯利康",
    "source": "https://www.harbourbiomed.cn/news/264.html"
  },
  {
    "id": 43,
    "category": "肿瘤",
    "date": "2021年7月1日",
    "month": "2021-07",
    "product": "EGFR",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "艾力斯",
    "licensee": "ArriVent",
    "source": ""
  },
  {
    "id": 44,
    "category": "自免",
    "date": "2026年7月14日",
    "month": "2026-07",
    "product": "CD40L",
    "productType": "单抗",
    "diseaseType": "",
    "licenser": "信达生物",
    "licensee": "Spero Therapeutics",
    "source": "https://www.drugtimes.cn/2026/07/15/11yimeiyuanxindazimiandankangchuhai/"
  },
  {
    "id": 45,
    "category": "自免",
    "date": "2026年7月14日",
    "month": "2026-07",
    "product": "IL-23R",
    "productType": "肽",
    "diseaseType": "",
    "licenser": "翰森制药",
    "licensee": "Avere Therapeutics",
    "source": "https://stock.finance.sina.com.cn/stock/go.php/vReport_Show/kind/search/rptid/837401785880/index.phtml"
  },
  {
    "id": 46,
    "category": "自免",
    "date": "2026年1月27日",
    "month": "2026-01",
    "product": "TL1A/IL23p19",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "先声药业",
    "licensee": "勃林格殷格翰（Boehringer Ingelheim）",
    "source": "https://m.163.com/news/article/KKACIHT5053270YS.html"
  },
  {
    "id": 47,
    "category": "自免",
    "date": "2025年6月26日",
    "month": "2025-06",
    "product": "IL11",
    "productType": "单抗",
    "diseaseType": "",
    "licenser": "迈威",
    "licensee": "Calico Life",
    "source": "https://mp.weixin.qq.com/s/-jGzUpzIDu489ba1wuMQ6Q"
  },
  {
    "id": 48,
    "category": "自免",
    "date": "2025年6月23日",
    "month": "2025-06",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "和铂",
    "licensee": "大塚制药",
    "source": "https://mp.weixin.qq.com/s/D56mwROLobkYa2ihY3Rr3g"
  },
  {
    "id": 49,
    "category": "自免",
    "date": "2024年11月18日",
    "month": "2024-11",
    "product": "TSLP、TSLP/IL-4R",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "博奥信",
    "licensee": "Aclaris Therapeutics",
    "source": "https://www.sec.gov/ix?doc=/Archives/edgar/data/1557746/000155837024015838/acrs-20241116x8k.htm  https://cn.biosion.com/news/datail/673b423b804acf5a200b92a8"
  },
  {
    "id": 50,
    "category": "自免",
    "date": "2024年11月7日",
    "month": "2024-11",
    "product": "CD3/BCMA/CD19",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "维立志博",
    "licensee": "Oblenio",
    "source": "https://www.leadsbiolabs.com/id45497156.html"
  },
  {
    "id": 51,
    "category": "自免",
    "date": "2024年10月29日",
    "month": "2024-10",
    "product": "CD3/CD19/CD20",
    "productType": "TCE",
    "diseaseType": "",
    "licenser": "恩沐生物",
    "licensee": "GSK",
    "source": "https://news.bioon.com/article/f564850019c9.html"
  },
  {
    "id": 52,
    "category": "自免",
    "date": "2024年7月9日",
    "month": "2024-07",
    "product": "未透露",
    "productType": "双抗",
    "diseaseType": "",
    "licenser": "康诺亚",
    "licensee": "Belenos",
    "source": "https://staticpacific.blob.core.windows.net/press-releases-attachments/2903339/HKEX-EPS_20240709_11280365_0.PDF"
  },
  {
    "id": 53,
    "category": "自免",
    "date": "2024年1月9日",
    "month": "2024-01",
    "product": "TSLP",
    "productType": "单抗",
    "diseaseType": "",
    "licenser": "Aiolos",
    "licensee": "GSK",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748878345&ver=6028&signature=GNSEYRREDK4ToIYhDX2oTmM7heQz6HQorz9HbMKp4A8*znj5alARrNdnSIHinnMbdq5QgsRpgA18-f7Mqb5Afp0Fkx6wa5SMl1FSclU6fZ6DJYd0WhMmLf4TNzAw-Iun&new=1"
  },
  {
    "id": 54,
    "category": "自免",
    "date": "2023年8月14日",
    "month": "2023-08",
    "product": "TSLP",
    "productType": "单抗",
    "diseaseType": "",
    "licenser": "恒瑞",
    "licensee": "One Bio",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748878236&ver=6028&signature=CIKsE1y98PV20svBZmapYRBV49Mo-bBOTpcu-yOFh-*WVapY5HKGjpTzmR9SR9PUpCzX*0I7G-lpkvcwhcmbgFxO9usGyzfzDabeQz*udoP-VCSIugV5OD6TB5zArXc5&new=1"
  },
  {
    "id": 55,
    "category": "自免",
    "date": "2021年3月1日",
    "month": "2021-03",
    "product": "TYK2",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "海思科",
    "licensee": "Alumis",
    "source": "https://xueqiu.com/4797094524/293423712"
  },
  {
    "id": 56,
    "category": "代谢",
    "date": "2026年4月8日",
    "month": "2026-04",
    "product": "GLP-1RA",
    "productType": "肽",
    "diseaseType": "代谢",
    "licenser": "甘李药业",
    "licensee": "JW Pharmaceutical",
    "source": "https://www.ganlee.com.cn/detail/1714.html"
  },
  {
    "id": 57,
    "category": "代谢",
    "date": "2026年3月29日",
    "month": "2026-03",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "代谢",
    "licenser": "英矽智能",
    "licensee": "礼来（Eli Lilly）",
    "source": "https://baijiahao.baidu.com/s?id=1861136706773433073&wfr=spider&for=pc"
  },
  {
    "id": 58,
    "category": "代谢",
    "date": "2026年2月23日",
    "month": "2026-02",
    "product": "未透露",
    "productType": "小核酸",
    "diseaseType": "慢性病/血脂异常等",
    "licenser": "前沿生物",
    "licensee": "GSK（葛兰素史克）",
    "source": "https://www.cnpharm.com/upload/resources/file/2026/02/24/185089.pdf"
  },
  {
    "id": 59,
    "category": "代谢",
    "date": "2025年8月1日",
    "month": "2025-08",
    "product": "APOC3",
    "productType": "小核酸",
    "diseaseType": "",
    "licenser": "Arrowhead",
    "licensee": "赛诺菲",
    "source": "https://mp.weixin.qq.com/s/IwTFUn6lOLhIBaZLupEXnA"
  },
  {
    "id": 60,
    "category": "代谢",
    "date": "2025年7月30日",
    "month": "2025-07",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "石药",
    "licensee": "Madrigal Pharmaceuticals",
    "source": "https://mp.weixin.qq.com/s/0FiGEL7MI80r0v9eSM94HQ"
  },
  {
    "id": 61,
    "category": "代谢",
    "date": "2025年7月28日",
    "month": "2025-07",
    "product": "PDE3/4",
    "productType": "小分子",
    "diseaseType": "",
    "licenser": "恒瑞",
    "licensee": "GSK",
    "source": "https://static.sse.com.cn/disclosure/listedinfo/announcement/c/new/2025-07-28/600276_20250728_7GZX.pdf"
  },
  {
    "id": 62,
    "category": "代谢",
    "date": "2025年6月2日",
    "month": "2025-06",
    "product": "GLP-1/GIP",
    "productType": "未透露",
    "diseaseType": "代谢",
    "licenser": "翰森",
    "licensee": "再生元",
    "source": "https://mp.weixin.qq.com/s/rkaiYETNNE7XHS94837BpQ"
  },
  {
    "id": 63,
    "category": "代谢",
    "date": "2025年3月25日",
    "month": "2025-03",
    "product": "脂蛋白a",
    "productType": "小分子",
    "diseaseType": "代谢",
    "licenser": "恒瑞",
    "licensee": "MSD",
    "source": "https://mp.weixin.qq.com/s/LPKi04Jk_7FnpckaTo8ZQA"
  },
  {
    "id": 64,
    "category": "代谢",
    "date": "2025年3月25日",
    "month": "2025-03",
    "product": "GLP-1/GIP/GCGR",
    "productType": "未透露",
    "diseaseType": "",
    "licenser": "联邦制药",
    "licensee": "诺和诺德",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748881762&ver=6028&signature=3spJKOZBcsO3xB5dn5ySAd8HHtvXhpeIiMhw8VQ4XQC6sBdIBORj5Lh7fTNoFjXgn2269PhHADJvBAHFKU7LIFd2HbPFhESWp9yPfy*G4nAxw7*9Db6-3aOp-AHHlADh&new=1"
  },
  {
    "id": 65,
    "category": "代谢",
    "date": "2024年12月18日",
    "month": "2024-12",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "代谢",
    "licenser": "翰森",
    "licensee": "默沙东",
    "source": "https://www.merck.com/news/merck-enters-into-exclusive-global-license-agreement-with-hansoh-pharma-for-investigational-oral-glp-1-receptor-agonist/"
  },
  {
    "id": 66,
    "category": "代谢",
    "date": "2024年10月8日",
    "month": "2024-10",
    "product": "脂蛋白a",
    "productType": "小分子",
    "diseaseType": "代谢",
    "licenser": "石药",
    "licensee": "AZ",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748881171&ver=6028&signature=ktmXthAkzOm8nj3lrGbeY4-gKDUjW8*Nd5ykHRxaqyamuwvTu9hJF8GQYo-fht6y*Bf7qVMW0SpO10BnGfXn0NYhXPxn*uYf9o70HwydUR9m0YBcAMY1UTbUCQECkTG*&new=1"
  }
];
