window.NEWS_DATA = [
  {
    "id": 1,
    "category": "肿瘤",
    "date": "2026年7月14日",
    "month": "2026-07",
    "product": "舒沃哲®（舒沃替尼）",
    "productType": "小分子（EGFR TKI）",
    "diseaseType": "肿瘤",
    "indication": "EGFR 20号外显子插入突变（exon20ins）非小细胞肺癌（NSCLC）",
    "stage": "已上市（中美获批）",
    "licenser": "迪哲医药",
    "licensee": "阿斯利康（AstraZeneca）",
    "upfront": "6亿",
    "upfrontType": "首付款（一次性、不可返还）",
    "totalValue": "15",
    "coop": "授权",
    "territory": "全球",
    "notes": "舒沃替尼为中美唯一获批口服EGFR exon20ins NSCLC靶向疗法；WU-KONG28 III期数据于2026 ASCO以LBA口头报告并发表于NEJM；一线适应症已递交中美上市申请",
    "source": "https://stockmc.xueqiu.com/202607/688192_20260714_LOKU.pdf"
  },
  {
    "id": 2,
    "category": "肿瘤",
    "date": "2026年7月2日",
    "month": "2026-07",
    "product": "AI药物发现合作（多靶点）",
    "productType": "AI制药/小分子（靶点未披露）",
    "diseaseType": "多个治疗领域（未披露）",
    "indication": "多个高潜力靶点（未披露）",
    "stage": "药物发现（临床前）",
    "licenser": "英矽智能（Insilico Medicine）",
    "licensee": "武田制药（Takeda）",
    "upfront": "6000万",
    "upfrontType": "项目启动费+近期里程碑付款",
    "totalValue": "6",
    "coop": "战略合作/授权",
    "territory": "全球",
    "notes": "英矽主导AI药物发现（Pharma.AI平台），武田负责全球开发与临床验证；继赛诺菲、默沙东后又一国际药企合作",
    "source": "https://xueqiu.com/S/03696/397968666"
  },
  {
    "id": 3,
    "category": "肿瘤",
    "date": "2026年6月30日",
    "month": "2026-06",
    "product": "MTS-128（三特异性TCE）",
    "productType": "三特异性TCE（T细胞衔接器）",
    "diseaseType": "未披露",
    "indication": "未披露",
    "stage": "临床前",
    "licenser": "剂泰科技",
    "licensee": "Boulevard Bio（Deerfield旗下）",
    "upfront": "2000万",
    "upfrontType": "首付款",
    "totalValue": "16.2",
    "coop": "授权",
    "territory": "全球",
    "notes": "创中国临床前TCE单笔海外授权金额纪录；基于自研AI纳米递送平台NanoForge开发",
    "source": "https://www.metispharma.com/qyxw/276.html"
  },
  {
    "id": 4,
    "category": "肿瘤",
    "date": "2026年5月29日",
    "month": "2026-05",
    "product": "12个肿瘤早期/源头创新项目（含ADC及多特异性抗体）",
    "productType": "多项目组合（ADC/多特异性抗体等）",
    "diseaseType": "肿瘤",
    "indication": "肿瘤（未逐一披露）",
    "stage": "早期/临床前（信达推进至I期）",
    "licenser": "信达生物",
    "licensee": "辉瑞（Pfizer）",
    "upfront": "6.5亿",
    "upfrontType": "首付款",
    "totalValue": "105",
    "coop": "全球战略许可及合作",
    "territory": "全球",
    "notes": "含信达8个早期管线及辉瑞提议的4个全新项目；信达负责推进至I期，辉瑞主导后续开发；双位数销售分成/利润共享",
    "source": "https://www.stcn.com/article/detail/3935413.html"
  },
  {
    "id": 5,
    "category": "肿瘤",
    "date": "2025年8月1日",
    "month": "2025-08",
    "product": "CTM012（DLL3）和CTM013（WT1？）",
    "productType": "TCE CD3 4-1BB三抗",
    "diseaseType": "",
    "indication": "",
    "stage": "临床前",
    "licenser": "乐普生物",
    "licensee": "Excalipoint 艾科联生物",
    "upfront": "1000万",
    "upfrontType": "首付款",
    "totalValue": "8.475",
    "coop": "授权/NewCo",
    "territory": "全球",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?__biz=Mzg3OTc3NjczMw==&mid=2247510833&idx=1&sn=377c6913ee70874923eb6a063134812e&poc_token=HIZqjWijufkhfRE6SX3XBrwU-LOlkvzvb_b-R6QQ"
  },
  {
    "id": 6,
    "category": "肿瘤",
    "date": "2025年6月26日",
    "month": "2025-06",
    "product": "G-CSF",
    "productType": "融合蛋白",
    "diseaseType": "",
    "indication": "于成年非髓性恶性肿瘤患者在接受容易引起发热性中性粒细胞减少症的骨髓抑制性抗癌药物治疗时，使用本品降低以发热性中性粒细胞减少症为表现的感染发生率。",
    "stage": "上市",
    "licenser": "迈威",
    "licensee": "齐鲁",
    "upfront": "3.8亿RMB",
    "upfrontType": "首付款",
    "totalValue": "5亿RMB",
    "coop": "授权",
    "territory": "中国大陆",
    "notes": "",
    "source": "https://stockmc.xueqiu.com/202506/688062_20250627_FLJL.pdf"
  },
  {
    "id": 7,
    "category": "肿瘤",
    "date": "2025年6月16日",
    "month": "2025-06",
    "product": "CDH6",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "实体瘤",
    "stage": "I期",
    "licenser": "先声再明",
    "licensee": "Nextcure",
    "upfront": "未透露",
    "upfrontType": "",
    "totalValue": "7.5",
    "coop": "",
    "territory": "全球（不包括中国内地）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/yXggs3-bMJUIEo9KiK05Cw"
  },
  {
    "id": 8,
    "category": "肿瘤",
    "date": "2025年6月5日",
    "month": "2025-06",
    "product": "CD3×BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "indication": "多发性骨髓瘤",
    "stage": "II期",
    "licenser": "智翔金泰",
    "licensee": "Cullinan",
    "upfront": "2000万",
    "upfrontType": "首付款",
    "totalValue": "16.9",
    "coop": "授权",
    "territory": "全球（不包括中国内地）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/6Q5c1ugE72Z85d8jUzSRQQ"
  },
  {
    "id": 9,
    "category": "肿瘤",
    "date": "2025年6月2日",
    "month": "2025-06",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "三阴性乳腺癌和小细胞肺癌",
    "stage": "III期",
    "licenser": "BioNtech",
    "licensee": "BMS",
    "upfront": "15亿",
    "upfrontType": "首付款",
    "totalValue": "20",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/peWaO6AbNss4jsgUIFeEmQ"
  },
  {
    "id": 10,
    "category": "肿瘤",
    "date": "2025年5月30日",
    "month": "2025-05",
    "product": "CLDN18.2",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "胃癌",
    "stage": "II期",
    "licenser": "信诺威",
    "licensee": "安斯泰来",
    "upfront": "1.3亿",
    "upfrontType": "1.3亿美元的首付款，并有资格收取最高7000万美元的近期付款",
    "totalValue": "13.4",
    "coop": "授权",
    "territory": "全球（除中国大陆、香港、澳门和台湾地区外）",
    "notes": "用于 CLDN18.2 表达的局部晚期不可切除或转移性 HER2 阴性胃或胃食管结合部腺癌的三线及以上治疗",
    "source": "https://mp.weixin.qq.com/s/ai1aG32GEmBA2Hj1_5Ol4g"
  },
  {
    "id": 11,
    "category": "肿瘤",
    "date": "2025年5月20日",
    "month": "2025-05",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "非小细胞肺癌（NSCLC）",
    "stage": "II期",
    "licenser": "三生制药",
    "licensee": "辉瑞",
    "upfront": "12.5亿",
    "upfrontType": "首付款",
    "totalValue": "48亿",
    "coop": "授权",
    "territory": "全球（不包括中国内地）",
    "notes": "",
    "source": "https://www.3sbio.com/news/details.aspx?id=307"
  },
  {
    "id": 12,
    "category": "肿瘤",
    "date": "2025年2月19日",
    "month": "2025-02",
    "product": "ROR1",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "肿瘤",
    "stage": "",
    "licenser": "石药",
    "licensee": "Radiance\nBiopharma",
    "upfront": "1500万",
    "upfrontType": "首付款",
    "totalValue": "1.5+10.75",
    "coop": "授权",
    "territory": "其中开发里程碑款项累计不超过1.5亿美元，销售里程碑款项累计不超过10.75亿美元。",
    "notes": "在美国、欧盟、英国、瑞士、挪威、冰岛、列支敦士登、阿尔巴尼亚、黑山、北马其顿、塞尔维亚、澳大利亚和加拿大开发和商业化SYS6005的独家权利",
    "source": "https://mp.weixin.qq.com/s/10DlZe9K5KExvweZARpFuw"
  },
  {
    "id": 13,
    "category": "肿瘤",
    "date": "2025年1月22日",
    "month": "2025-01",
    "product": "CDH17",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "肿瘤",
    "stage": "pre-IND",
    "licenser": "乐普生物",
    "licensee": "ArriVent Biopharma",
    "upfront": "4700万",
    "upfrontType": "首付和近期里程碑",
    "totalValue": "11.6",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://www.lepubiopharma.com/new/216.html"
  },
  {
    "id": 14,
    "category": "肿瘤",
    "date": "2025年1月13日",
    "month": "2025-01",
    "product": "SIM0500(GPRC5D-BCMA-CD3)",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "多发性骨髓瘤",
    "stage": "I期",
    "licenser": "先声再明",
    "licensee": "Abbvie",
    "upfront": "未公布",
    "upfrontType": "",
    "totalValue": "10.55",
    "coop": "授权",
    "territory": "大中华地区",
    "notes": "",
    "source": "https://www.simcere.com/news/detail.aspx?mtt=1485"
  },
  {
    "id": 15,
    "category": "肿瘤",
    "date": "2025年1月8日",
    "month": "2025-01",
    "product": "EGFR/HER3",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "IND",
    "licenser": "映恩",
    "licensee": "Avenzo",
    "upfront": "5000万",
    "upfrontType": "首付款",
    "totalValue": "11.5",
    "coop": "授权",
    "territory": "全球（除大中华区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/dwruRrwz4bLVfF_lOli-Dg"
  },
  {
    "id": 16,
    "category": "肿瘤",
    "date": "2025年1月2日",
    "month": "2025-01",
    "product": "DLL3",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "SCLC",
    "stage": "临床I期",
    "licenser": "信达",
    "licensee": "罗氏",
    "upfront": "8000万",
    "upfrontType": "首付款",
    "totalValue": "10",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/jEdc_W_Pqkcl9erIdk-kFQ"
  },
  {
    "id": 17,
    "category": "肿瘤",
    "date": "2024年12月29日",
    "month": "2024-12",
    "product": "DLL3",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "临床I期",
    "licenser": "恒瑞",
    "licensee": "IDEAYA",
    "upfront": "7500万",
    "upfrontType": "首付款",
    "totalValue": "2",
    "coop": "授权",
    "territory": "全球（除大中华区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/KaqNt4gtAiYcA0LKl24_sw"
  },
  {
    "id": 18,
    "category": "肿瘤",
    "date": "2024年12月4日",
    "month": "2024-12",
    "product": "DB-1324\nADAM9/CDH17?",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "licenser": "映恩生物",
    "licensee": "GSK",
    "upfront": "3000万",
    "upfrontType": "预付款及其他行权前里程碑付款",
    "totalValue": "9.75亿",
    "coop": "授权",
    "territory": "全球范围内（中国大陆、香港地区和澳门地区除外）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1733303268&ver=5668&signature=bHt7tKfzKB5kSTn3cy4Cnmmyzk1bv*6ew8Hcgu5E8jwbKnnUdqXp6urtvPwcXOpOIq-UCU0eBHbOBFPvI6*DRLV6-7ZlfGdA6HMoI4jmq3SHEorrXYQTcK2fPYCKWym5&new=1"
  },
  {
    "id": 19,
    "category": "肿瘤",
    "date": "2024年11月18日",
    "month": "2024-11",
    "product": "TROP2/NECTIN4",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "licenser": "橙帆医药",
    "licensee": "Avenzo",
    "upfront": "5000万",
    "upfrontType": "首付款及近期里程碑付款",
    "totalValue": "7.5",
    "coop": "授权",
    "territory": "全球范围（不包括大中华区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/XjkYoCEeG7k1r6pNerZMlw https://mp.weixin.qq.com/s/tP7di-D-VS_2NwatpbE4ww\nhttps://mp.weixin.qq.com/s?src=11&timestamp=1733492444&ver=5672&signature=26M3E7w6a8KE0wBWvsSoAXc1tHjwtg7MFJgh-buFxcco8CAS29622cZB8H5q*wNTV2q2Gxlyj7qL*ItfRDEmP9HPIW5XIQCp4ZteynYjhSv1eRcS8T8F3d7L*F2ITfM1&new=1"
  },
  {
    "id": 20,
    "category": "肿瘤",
    "date": "2024年11月17日",
    "month": "2024-11",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "療復發或難治性多發性骨髓瘤",
    "stage": "I/II期",
    "licenser": "康诺亚",
    "licensee": "Platina Medicines Ltd",
    "upfront": "1600万",
    "upfrontType": "首付款和\n近期付款",
    "totalValue": "6.1",
    "coop": "NewCo",
    "territory": "全球（不包括中國內\n地、香港、澳門及台灣）",
    "notes": "",
    "source": "https://staticpacific.blob.core.windows.net/press-releases-attachments/3504798/HKEX-EPS_20241117_11442884_0.PDF"
  },
  {
    "id": 21,
    "category": "肿瘤",
    "date": "2024年11月14日",
    "month": "2024-11",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "I期招募中",
    "licenser": "礼新",
    "licensee": "默沙东",
    "upfront": "5.88亿",
    "upfrontType": "首付款",
    "totalValue": "27",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://www.msdchina.com.cn/2024/11/14/company_news_2024-11-14/"
  },
  {
    "id": 22,
    "category": "肿瘤",
    "date": "2024年11月13日",
    "month": "2024-11",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "三阴性乳腺癌和小细胞肺癌",
    "stage": "III期",
    "licenser": "普米斯",
    "licensee": "BioNTech SE",
    "upfront": "8亿",
    "upfrontType": "100%已发行股本",
    "totalValue": "",
    "coop": "收购",
    "territory": "",
    "notes": "1、已有700多名患者接受了临床试验/2、和映恩的TROP2-ADC在做联用；3、南通生产基地；4、300多名员工",
    "source": "https://www.sec.gov/Archives/edgar/data/1776985/000177698524000094/a99_1biontechtoacquirebiot.htmhttps://cn.biotheus.com/news/344.html"
  },
  {
    "id": 23,
    "category": "肿瘤",
    "date": "2024年9月4日",
    "month": "2024-09",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "多发性骨髓瘤",
    "stage": "I期",
    "licenser": "岸迈生物",
    "licensee": "Vignette",
    "upfront": "6000万",
    "upfrontType": "现金和Vignette股权",
    "totalValue": "5.75",
    "coop": "NewCo",
    "territory": "大中华区（包括中国大陆，香港，澳门和台湾地区）以外",
    "notes": "",
    "source": "https://www.epimab.com/cn/news/41"
  },
  {
    "id": 24,
    "category": "肿瘤",
    "date": "2024年8月30日",
    "month": "2024-08",
    "product": "KRAS G12C抑制剂戈来雷塞和SHP2抑制剂JAB-3312",
    "productType": "小分子",
    "diseaseType": "肿瘤",
    "indication": "KRAS G12C突变的晚期或转移性非小细胞肺癌患者",
    "stage": "III期",
    "licenser": "加科思",
    "licensee": "艾力斯",
    "upfront": "1.5亿RMB",
    "upfrontType": "首付款",
    "totalValue": "7",
    "coop": "授权",
    "territory": "中国（包括中国大陆、香港、澳门和台湾地区）",
    "notes": "",
    "source": "https://www.allist.com.cn/newsd/101/2086.html"
  },
  {
    "id": 25,
    "category": "肿瘤",
    "date": "2024年8月19日",
    "month": "2024-08",
    "product": "未披露",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肺癌、消化道肿瘤等多种实体瘤",
    "stage": "临床前",
    "licenser": "科伦博泰",
    "licensee": "默沙东",
    "upfront": "3750万",
    "upfrontType": "",
    "totalValue": "未披露",
    "coop": "授权",
    "territory": "未披露",
    "notes": "",
    "source": ""
  },
  {
    "id": 26,
    "category": "肿瘤",
    "date": "2024年8月9日",
    "month": "2024-08",
    "product": "CD3/CD19",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "B细胞肿瘤",
    "stage": "1期和1b/2期",
    "licenser": "同润生物",
    "licensee": "默沙东",
    "upfront": "7亿",
    "upfrontType": "首付款",
    "totalValue": "6",
    "coop": "转让",
    "territory": "全球",
    "notes": "",
    "source": "https://www.msdchina.com.cn/2024/08/09/company_news/"
  },
  {
    "id": 27,
    "category": "肿瘤",
    "date": "2024年8月5日",
    "month": "2024-08",
    "product": "CD3/CD20",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "I期",
    "licenser": "嘉和生物",
    "licensee": "TRC2004",
    "upfront": "数千万",
    "upfrontType": "首付款",
    "totalValue": "4.43",
    "coop": "NewCo",
    "territory": "全球独家许可（不包括中国大陆、香港、澳门及台湾）",
    "notes": "TRC 2004被许可人数量可观的股权",
    "source": "https://www.genorbio.com/cn/media/corporate-news/20240805/"
  },
  {
    "id": 28,
    "category": "肿瘤",
    "date": "2024年8月1日",
    "month": "2024-08",
    "product": "PD-L1/VEGF和CTLA-4",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "三阴性乳腺癌和非小细胞肺癌",
    "stage": "I期",
    "licenser": "宜明昂科",
    "licensee": "SynBioTx (Instil Bio)",
    "upfront": "1,000万",
    "upfrontType": "首付款",
    "totalValue": "20",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://www.sec.gov/Archives/edgar/data/1789769/000178976924000077/til-20240801.htm  http://www.immuneonco.com/news/gsdynamics/583.html"
  },
  {
    "id": 29,
    "category": "肿瘤",
    "date": "2024年6月18日",
    "month": "2024-06",
    "product": "PTK7",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "IND",
    "licenser": "麦科思/普众",
    "licensee": "Day One",
    "upfront": "5500 万",
    "upfrontType": "首付款",
    "totalValue": "11.52",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://news.qq.com/rain/a/20240619A06J5O00"
  },
  {
    "id": 30,
    "category": "肿瘤",
    "date": "2023年12月28日",
    "month": "2023-12",
    "product": "PD-L1/SIRPα",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "licenser": "科望医药",
    "licensee": "安斯泰来",
    "upfront": "3700万",
    "upfrontType": "首付款和行权费",
    "totalValue": "17",
    "coop": "合作开发及授权",
    "territory": "",
    "notes": "另一分子未公开",
    "source": "https://www.astellas.com/en/news/28816"
  },
  {
    "id": 31,
    "category": "肿瘤",
    "date": "2023年12月12日",
    "month": "2023-12",
    "product": "EGFR/HER3",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "在转移性或不可切除的非小细胞肺癌（NSCLC）",
    "stage": "I期",
    "licenser": "百利天恒",
    "licensee": "BMS",
    "upfront": "8亿",
    "upfrontType": "首付款",
    "totalValue": "84",
    "coop": "授权",
    "territory": "中国大陆以外",
    "notes": "SystImmune 将通过其关联公司独家负责 BL-B01D1 在中国大陆的开发、商业化以及在中国大陆的生产，并负责生产部分供中国大陆以外地区使用的药品。BMS 将独家负责 BL-B01D1 在全球其他地区的开发和商业化。",
    "source": "http://www.baili-pharm.com/upload/2023-12-12/128238727.pdf"
  },
  {
    "id": 32,
    "category": "肿瘤",
    "date": "2023年11月6日",
    "month": "2023-11",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "实体瘤",
    "stage": "中国II期",
    "licenser": "普米斯",
    "licensee": "BioNTech SE",
    "upfront": "5500万",
    "upfrontType": "首付款",
    "totalValue": "10",
    "coop": "授权",
    "territory": "全球（大中华区除外）",
    "notes": "",
    "source": "https://cn.biotheus.com/news/333.html"
  },
  {
    "id": 33,
    "category": "肿瘤",
    "date": "2023年1月5日",
    "month": "2023-01",
    "product": "4款TCE双抗",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "licenser": "药明生物",
    "licensee": "GSK",
    "upfront": "4000万",
    "upfrontType": "首付款",
    "totalValue": "14.6",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://www.wuxibiologics.com.cn/wuxi-biologics-and-gsk-enter-into-license-agreement-on-multiple-novel-bi-multi-specific-t-cell-engagers/"
  },
  {
    "id": 34,
    "category": "肿瘤",
    "date": "2022年12月6日",
    "month": "2022-12",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "非小细胞肺癌",
    "stage": "III期",
    "licenser": "康方生物",
    "licensee": "Summit Therapeutics",
    "upfront": "5亿",
    "upfrontType": "首付款",
    "totalValue": "50亿",
    "coop": "授权",
    "territory": "美国、加拿大、欧洲和日本",
    "notes": "",
    "source": "https://www.akesobio.com/cn/media/akeso-news/20221206/"
  },
  {
    "id": 35,
    "category": "肿瘤",
    "date": "2022年4月7日",
    "month": "2022-04",
    "product": "CD3/CLDN18.2",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "licenser": "和铂医药",
    "licensee": "阿斯利康",
    "upfront": "2500万",
    "upfrontType": "预付款",
    "totalValue": "3.25",
    "coop": "转让",
    "territory": "全球",
    "notes": "",
    "source": "https://www.harbourbiomed.cn/news/264.html"
  },
  {
    "id": 36,
    "category": "肿瘤",
    "date": "2021年7月1日",
    "month": "2021-07",
    "product": "甲磺酸伏美替尼",
    "productType": "小分子",
    "diseaseType": "肿瘤",
    "indication": "目前已获批用于EGFR突变非小细胞肺癌患者的二线治疗，具有“双活性、高选择、强缩瘤、安全佳”的特点。",
    "stage": "",
    "licenser": "艾力斯",
    "licensee": "ArriVent Biopharma",
    "upfront": "4000万",
    "upfrontType": "首付款",
    "totalValue": "7.65",
    "coop": "NewCo",
    "territory": "除中国大陆、中国台湾、中国香港和中国澳门外",
    "notes": "",
    "source": ""
  },
  {
    "id": 37,
    "category": "自免",
    "date": "2025年6月26日",
    "month": "2025-06",
    "product": "IL11",
    "productType": "单抗",
    "diseaseType": "",
    "indication": "自免（年龄相关疾病）",
    "stage": "I期",
    "licenser": "迈威",
    "licensee": "Calico Life",
    "upfront": "2500万",
    "upfrontType": "首付款",
    "totalValue": "4.71",
    "coop": "授权",
    "territory": "全球（除大中华区外）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/-jGzUpzIDu489ba1wuMQ6Q"
  },
  {
    "id": 38,
    "category": "自免",
    "date": "2025年6月23日",
    "month": "2025-06",
    "product": "CD3×BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "indication": "自免",
    "stage": "IND",
    "licenser": "和铂",
    "licensee": "大塚制药",
    "upfront": "4700万",
    "upfrontType": "首付和近期里程碑",
    "totalValue": "7",
    "coop": "授权",
    "territory": "全球（除大中华区外）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/D56mwROLobkYa2ihY3Rr3g"
  },
  {
    "id": 39,
    "category": "自免",
    "date": "2024年11月18日",
    "month": "2024-11",
    "product": "TSLP、TSLP/IL-4R",
    "productType": "双抗",
    "diseaseType": "自免",
    "indication": "重度特应性皮炎；重症哮喘和慢性鼻窦炎伴鼻息肉",
    "stage": "TSLP美国2a中国2期, 双抗临床前",
    "licenser": "博奥信",
    "licensee": "Aclaris Therapeutics",
    "upfront": "3000万",
    "upfrontType": "首付款以及承担部分开发成本和药物产品材料费用",
    "totalValue": "9",
    "coop": "NewCo",
    "territory": "全球（除大中华区外）",
    "notes": "",
    "source": "https://www.sec.gov/ix?doc=/Archives/edgar/data/1557746/000155837024015838/acrs-20241116x8k.htm  https://cn.biosion.com/news/datail/673b423b804acf5a200b92a8"
  },
  {
    "id": 40,
    "category": "自免",
    "date": "2024年11月7日",
    "month": "2024-11",
    "product": "CD3/BCMA/CD19",
    "productType": "TCE",
    "diseaseType": "自免",
    "indication": "自免",
    "stage": "临床前",
    "licenser": "维立志博",
    "licensee": "Oblenio",
    "upfront": "3500万",
    "upfrontType": "首付款和近期付款",
    "totalValue": "5.79",
    "coop": "NewCo",
    "territory": "",
    "notes": "",
    "source": "https://www.leadsbiolabs.com/id45497156.html"
  },
  {
    "id": 41,
    "category": "自免",
    "date": "2024年10月29日",
    "month": "2024-10",
    "product": "CD3/CD19/CD20",
    "productType": "TCE",
    "diseaseType": "自免",
    "indication": "系统性红斑狼疮（SLE）和狼疮性肾炎（LN）",
    "stage": "I期",
    "licenser": "恩沐生物",
    "licensee": "GSK",
    "upfront": "3亿",
    "upfrontType": "首付款",
    "totalValue": "5.5",
    "coop": "授权",
    "territory": "",
    "notes": "",
    "source": "https://news.bioon.com/article/f564850019c9.html"
  },
  {
    "id": 42,
    "category": "自免",
    "date": "2024年7月9日",
    "month": "2024-07",
    "product": "2款自免双抗 CM512（推测IL13/TSLP）及CM536",
    "productType": "双抗",
    "diseaseType": "自免",
    "indication": "自免",
    "stage": "未知",
    "licenser": "康诺亚",
    "licensee": "Belenos",
    "upfront": "1500万",
    "upfrontType": "首付款和近期付款",
    "totalValue": "1.75",
    "coop": "NewCo",
    "territory": "全球（不包括大中華地區）",
    "notes": "",
    "source": "https://staticpacific.blob.core.windows.net/press-releases-attachments/2903339/HKEX-EPS_20240709_11280365_0.PDF"
  },
  {
    "id": 43,
    "category": "自免",
    "date": "2024年1月9日",
    "month": "2024-01",
    "product": "TSLP",
    "productType": "单抗",
    "diseaseType": "自免",
    "indication": "中重度哮喘",
    "stage": "",
    "licenser": "Aiolos",
    "licensee": "GSK",
    "upfront": "10亿",
    "upfrontType": "预付款",
    "totalValue": "4",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "Aiolos公司表示，阻断TSLP是唯一能对所有类型的中重度哮喘产生临床疗效的生物方法。",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748878345&ver=6028&signature=GNSEYRREDK4ToIYhDX2oTmM7heQz6HQorz9HbMKp4A8*znj5alARrNdnSIHinnMbdq5QgsRpgA18-f7Mqb5Afp0Fkx6wa5SMl1FSclU6fZ6DJYd0WhMmLf4TNzAw-Iun&new=1"
  },
  {
    "id": 44,
    "category": "自免",
    "date": "2023年8月14日",
    "month": "2023-08",
    "product": "TSLP",
    "productType": "单抗",
    "diseaseType": "自免",
    "indication": "中重度哮喘",
    "stage": "",
    "licenser": "恒瑞",
    "licensee": "One Bio",
    "upfront": "2150",
    "upfrontType": "首付款",
    "totalValue": "10.25",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748878236&ver=6028&signature=CIKsE1y98PV20svBZmapYRBV49Mo-bBOTpcu-yOFh-*WVapY5HKGjpTzmR9SR9PUpCzX*0I7G-lpkvcwhcmbgFxO9usGyzfzDabeQz*udoP-VCSIugV5OD6TB5zArXc5&new=1"
  },
  {
    "id": 45,
    "category": "自免",
    "date": "2021年3月1日",
    "month": "2021-03",
    "product": "TYK2抑制剂",
    "productType": "小分子",
    "diseaseType": "自免",
    "indication": "中度至重度斑块状银屑病、SLE",
    "stage": "临床前",
    "licenser": "海思科",
    "licensee": "Alumis",
    "upfront": "6000万",
    "upfrontType": "首付款",
    "totalValue": "1.2",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "https://xueqiu.com/4797094524/293423712"
  },
  {
    "id": 46,
    "category": "代谢",
    "date": "2025年8月1日",
    "month": "2025-08",
    "product": "APOC3",
    "productType": "RNAi",
    "diseaseType": "",
    "indication": "家族性乳糜微粒血症综合征（FCS）、严重高甘油三酯血症（SHTG）及混合性高脂血症",
    "stage": "3期成功准备上市",
    "licenser": "Arrowhead（维亚臻母公司）",
    "licensee": "赛诺菲",
    "upfront": "1.3亿",
    "upfrontType": "首付款",
    "totalValue": "最高2.65亿美元（基于中国适应症获批进展）",
    "coop": "授权",
    "territory": "大中华区",
    "notes": "维亚臻是Arrowhead在国内和Vivo一起成立的子公司",
    "source": "https://mp.weixin.qq.com/s/IwTFUn6lOLhIBaZLupEXnA"
  },
  {
    "id": 47,
    "category": "代谢",
    "date": "2025年7月30日",
    "month": "2025-07",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "",
    "indication": "MASH",
    "stage": "临床前",
    "licenser": "石药",
    "licensee": "Madrigal Pharmaceuticals",
    "upfront": "1.2亿",
    "upfrontType": "首付款",
    "totalValue": "20.75",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "Madrigal有THR-β治疗MASH",
    "source": "https://mp.weixin.qq.com/s/0FiGEL7MI80r0v9eSM94HQ"
  },
  {
    "id": 48,
    "category": "代谢",
    "date": "2025年7月28日",
    "month": "2025-07",
    "product": "HRS-9821（PDE3/4双重阻断小分子，临床I期）和其他11个项目（临床前）",
    "productType": "小分子",
    "diseaseType": "",
    "indication": "COPD",
    "stage": "最晚I期",
    "licenser": "恒瑞",
    "licensee": "GSK",
    "upfront": "5亿",
    "upfrontType": "首付款",
    "totalValue": "120亿",
    "coop": "授权",
    "territory": "大中华区外",
    "notes": "",
    "source": "https://static.sse.com.cn/disclosure/listedinfo/announcement/c/new/2025-07-28/600276_20250728_7GZX.pdf"
  },
  {
    "id": 49,
    "category": "代谢",
    "date": "2025年6月2日",
    "month": "2025-06",
    "product": "GLP-1/GIP",
    "productType": "",
    "diseaseType": "代谢",
    "indication": "",
    "stage": "中国III期",
    "licenser": "翰森",
    "licensee": "再生元",
    "upfront": "8000万",
    "upfrontType": "首付款",
    "totalValue": "19.3",
    "coop": "授权",
    "territory": "全球独占许可（不含中国内地、香港及澳门）。",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/rkaiYETNNE7XHS94837BpQ"
  },
  {
    "id": 50,
    "category": "代谢",
    "date": "2025年3月25日",
    "month": "2025-03",
    "product": "脂蛋白(a)[Lp(a)]",
    "productType": "小分子",
    "diseaseType": "代谢",
    "indication": "降脂",
    "stage": "2期",
    "licenser": "恒瑞",
    "licensee": "MSD",
    "upfront": "2亿",
    "upfrontType": "首付款",
    "totalValue": "17.7",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/LPKi04Jk_7FnpckaTo8ZQA"
  },
  {
    "id": 51,
    "category": "代谢",
    "date": "2025年3月25日",
    "month": "2025-03",
    "product": "GLP-1、GIP和胰高血糖素受体三重激动剂",
    "productType": "",
    "diseaseType": "",
    "indication": "肥胖症、2型糖尿病",
    "stage": "1b期试验",
    "licenser": "联邦制药",
    "licensee": "诺和诺德",
    "upfront": "2亿",
    "upfrontType": "首付款",
    "totalValue": "18",
    "coop": "授权",
    "territory": "全球（除中国大陆、香港、澳门和台湾地区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748881762&ver=6028&signature=3spJKOZBcsO3xB5dn5ySAd8HHtvXhpeIiMhw8VQ4XQC6sBdIBORj5Lh7fTNoFjXgn2269PhHADJvBAHFKU7LIFd2HbPFhESWp9yPfy*G4nAxw7*9Db6-3aOp-AHHlADh&new=1"
  },
  {
    "id": 52,
    "category": "代谢",
    "date": "2024年12月18日",
    "month": "2024-12",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "代谢",
    "indication": "",
    "stage": "临床前",
    "licenser": "翰森",
    "licensee": "默沙东",
    "upfront": "1.12亿",
    "upfrontType": "首付款",
    "totalValue": "18",
    "coop": "授权",
    "territory": "全球（在特定条件下，翰森制药可能会在中国共同推广或独家商业化）",
    "notes": "口服小分子",
    "source": "https://www.merck.com/news/merck-enters-into-exclusive-global-license-agreement-with-hansoh-pharma-for-investigational-oral-glp-1-receptor-agonist/"
  },
  {
    "id": 53,
    "category": "代谢",
    "date": "2024年10月8日",
    "month": "2024-10",
    "product": "脂蛋白(a)[Lp(a)]",
    "productType": "小分子",
    "diseaseType": "代谢",
    "indication": "降脂",
    "stage": "临床前",
    "licenser": "石药",
    "licensee": "AZ",
    "upfront": "1亿",
    "upfrontType": "首付款",
    "totalValue": "19.2",
    "coop": "转让",
    "territory": "全球权益",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748881171&ver=6028&signature=ktmXthAkzOm8nj3lrGbeY4-gKDUjW8*Nd5ykHRxaqyamuwvTu9hJF8GQYo-fht6y*Bf7qVMW0SpO10BnGfXn0NYhXPxn*uYf9o70HwydUR9m0YBcAMY1UTbUCQECkTG*&new=1"
  },
  {
    "id": 54,
    "category": "BCG项目",
    "date": "2024年12月3日",
    "month": "2024-12",
    "product": "OSMR",
    "productType": "单抗",
    "diseaseType": "自免",
    "indication": "",
    "stage": "TOP6",
    "licenser": "",
    "licensee": "Prism Medicines",
    "upfront": "排他费：10+10\noption：100",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": ""
  },
  {
    "id": 55,
    "category": "BCG项目",
    "date": "2024年11月13日",
    "month": "2024-11",
    "product": "GUCY2C",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "binder",
    "licenser": "百奥赛图",
    "licensee": "",
    "upfront": "first option:1.5万\nsecond option：8.5万\nopition：30万",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": ""
  },
  {
    "id": 56,
    "category": "BCG项目",
    "date": "2024年6月30日",
    "month": "2024-06",
    "product": "BCG034（B7H3/PTK7）",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "PCC",
    "licenser": "百奥赛图",
    "licensee": "IDEAYA",
    "upfront": "50\nOption Exercise Fee：600",
    "upfrontType": "",
    "totalValue": "",
    "coop": "授权",
    "territory": "全球",
    "notes": "保留TPD",
    "source": ""
  },
  {
    "id": 57,
    "category": "BCG项目",
    "date": "2023年12月21日",
    "month": "2023-12",
    "product": "YH012 (HER2/TROP2)",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "PCC",
    "licenser": "百奥赛图",
    "licensee": "Radiance",
    "upfront": "50（25+25）\noption：500万（250+250）",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": ""
  },
  {
    "id": 58,
    "category": "BCG项目",
    "date": "2024年3月14日",
    "month": "2024-03",
    "product": "BSA01（EGFR/MUC1）",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "",
    "licenser": "百奥赛图",
    "licensee": "ABL",
    "upfront": "100",
    "upfrontType": "",
    "totalValue": "",
    "coop": "授权",
    "territory": "全球",
    "notes": "EGFR/MUC1 target pair for any ADC, excluding nucleic acid or TPD.",
    "source": ""
  },
  {
    "id": 59,
    "category": "BCG项目",
    "date": "2023年2月17日",
    "month": "2023-02",
    "product": "YH008（PD-1/CD40）",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "pre-IND",
    "licenser": "百奥赛图",
    "licensee": "微芯生物",
    "upfront": "4000RMB",
    "upfrontType": "",
    "totalValue": "",
    "coop": "授权",
    "territory": "大中华区（包括港澳台）",
    "notes": "",
    "source": ""
  },
  {
    "id": 60,
    "category": "BCG项目",
    "date": "2022年6月24日",
    "month": "2022-06",
    "product": "DM001（EGFR/TROP2）",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "PCC",
    "licenser": "百奥赛图",
    "licensee": "多玛",
    "upfront": "2000RMB",
    "upfrontType": "",
    "totalValue": "",
    "coop": "转让",
    "territory": "全球",
    "notes": "",
    "source": ""
  },
  {
    "id": 61,
    "category": "BCG项目",
    "date": "2023年6月28日",
    "month": "2023-06",
    "product": "DM005（EGFR/MET）",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "PCC",
    "licenser": "百奥赛图",
    "licensee": "多玛",
    "upfront": "2000RMB",
    "upfrontType": "",
    "totalValue": "",
    "coop": "转让",
    "territory": "全球",
    "notes": "",
    "source": ""
  },
  {
    "id": 62,
    "category": "BCG项目",
    "date": "2024年6月14日",
    "month": "2024-06",
    "product": "BCG019(EGFR/HER3)",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "PCC",
    "licenser": "百奥赛图",
    "licensee": "Astellas",
    "upfront": "120万，排他MTA",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": ""
  }
];
