window.NEWS_DATA = [
  {
    "category": "肿瘤",
    "date": "2025年8月1日",
    "month": "2025-08",
    "product": "CTM012（DLL3）和CTM013（WT1？）",
    "productType": "TCE CD3 4-1BB三抗",
    "diseaseType": "",
    "indication": "",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "乐普生物",
    "licensee": "Excalipoint 艾科联生物",
    "upfront": "1000万",
    "upfrontType": "首付款",
    "totalValue": "8.475",
    "coop": "授权/NewCo",
    "territory": "全球",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?__biz=Mzg3OTc3NjczMw==&mid=2247510833&idx=1&sn=377c6913ee70874923eb6a063134812e&poc_token=HIZqjWijufkhfRE6SX3XBrwU-LOlkvzvb_b-R6QQ",
    "id": 1,
    "summary": "2025年8月1日，乐普生物 与 Excalipoint 艾科联生物 就 授权/NewCo达成合作。交易标的为 CTM012（DLL3）和CTM013（WT1？）（TCE CD3 4-1BB三抗）。项目当前处于 临床前 阶段。首付款 1000万（首付款），潜在总交易额 8.475。合作地域覆盖 全球。"
  },
  {
    "category": "代谢",
    "date": "2025年8月1日",
    "month": "2025-08",
    "product": "APOC3",
    "productType": "RNAi",
    "diseaseType": "",
    "indication": "家族性乳糜微粒血症综合征（FCS）、严重高甘油三酯血症（SHTG）及混合性高脂血症",
    "stage": "3期成功准备上市",
    "stageNorm": "上市",
    "licenser": "Arrowhead（维亚臻母公司）",
    "licensee": "赛诺菲",
    "upfront": "1.3亿",
    "upfrontType": "首付款",
    "totalValue": "最高2.65亿美元（基于中国适应症获批进展）",
    "coop": "授权",
    "territory": "大中华区",
    "notes": "维亚臻是Arrowhead在国内和Vivo一起成立的子公司",
    "source": "https://mp.weixin.qq.com/s/IwTFUn6lOLhIBaZLupEXnA",
    "id": 2,
    "summary": "2025年8月1日，Arrowhead（维亚臻母公司） 与 赛诺菲 就 授权达成合作。交易标的为 APOC3（RNAi、家族性乳糜微粒血症综合征（FCS）、严重高甘油三酯血症（SHTG）及混合性高脂血症）。项目当前处于 3期成功准备上市 阶段。首付款 1.3亿（首付款），潜在总交易额 最高2.65亿美元（基于中国适应症获批进展）。合作地域覆盖 大中华区。维亚臻是Arrowhead在国内和Vivo一起成立的子公司"
  },
  {
    "category": "代谢",
    "date": "2025年7月30日",
    "month": "2025-07",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "",
    "indication": "MASH",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "石药",
    "licensee": "Madrigal Pharmaceuticals",
    "upfront": "1.2亿",
    "upfrontType": "首付款",
    "totalValue": "20.75",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "Madrigal有THR-β治疗MASH",
    "source": "https://mp.weixin.qq.com/s/0FiGEL7MI80r0v9eSM94HQ",
    "id": 3,
    "summary": "2025年7月30日，石药 与 Madrigal Pharmaceuticals 就 授权达成合作。交易标的为 GLP-1（小分子、MASH）。项目当前处于 临床前 阶段。首付款 1.2亿（首付款），潜在总交易额 20.75。合作地域覆盖 大中华区以外。Madrigal有THR-β治疗MASH"
  },
  {
    "category": "代谢",
    "date": "2025年7月28日",
    "month": "2025-07",
    "product": "HRS-9821（PDE3/4双重阻断小分子，临床I期）和其他11个项目（临床前）",
    "productType": "小分子",
    "diseaseType": "",
    "indication": "COPD",
    "stage": "最晚I期",
    "stageNorm": "其他",
    "licenser": "恒瑞",
    "licensee": "GSK",
    "upfront": "5亿",
    "upfrontType": "首付款",
    "totalValue": "120亿",
    "coop": "授权",
    "territory": "大中华区外",
    "notes": "",
    "source": "https://static.sse.com.cn/disclosure/listedinfo/announcement/c/new/2025-07-28/600276_20250728_7GZX.pdf",
    "id": 4,
    "summary": "2025年7月28日，恒瑞 与 GSK 就 授权达成合作。交易标的为 HRS-9821（PDE3/4双重阻断小分子，临床I期）和其他11个项目（临床前）（小分子、COPD）。项目当前处于 最晚I期 阶段。首付款 5亿（首付款），潜在总交易额 120亿。合作地域覆盖 大中华区外。"
  },
  {
    "category": "肿瘤",
    "date": "2025年6月26日",
    "month": "2025-06",
    "product": "G-CSF",
    "productType": "融合蛋白",
    "diseaseType": "",
    "indication": "于成年非髓性恶性肿瘤患者在接受容易引起发热性中性粒细胞减少症的骨髓抑制性抗癌药物治疗时，使用本品降低以发热性中性粒细胞减少症为表现的感染发生率。",
    "stage": "上市",
    "stageNorm": "上市",
    "licenser": "迈威",
    "licensee": "齐鲁",
    "upfront": "3.8亿RMB",
    "upfrontType": "首付款",
    "totalValue": "5亿RMB",
    "coop": "授权",
    "territory": "中国大陆",
    "notes": "",
    "source": "https://stockmc.xueqiu.com/202506/688062_20250627_FLJL.pdf",
    "id": 5,
    "summary": "2025年6月26日，迈威 与 齐鲁 就 授权达成合作。交易标的为 G-CSF（融合蛋白、于成年非髓性恶性肿瘤患者在接受容易引起发热性中性粒细胞减少症的骨髓抑制性抗癌药物治疗时，使用本品降低以发热性中性粒细胞减少症为表现的感染发生率。）。项目当前处于 上市 阶段。首付款 3.8亿RMB（首付款），潜在总交易额 5亿RMB。合作地域覆盖 中国大陆。"
  },
  {
    "category": "肿瘤",
    "date": "2025年6月16日",
    "month": "2025-06",
    "product": "CDH6",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "实体瘤",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "先声再明",
    "licensee": "Nextcure",
    "upfront": "未透露",
    "upfrontType": "",
    "totalValue": "7.5",
    "coop": "",
    "territory": "全球（不包括中国内地）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/yXggs3-bMJUIEo9KiK05Cw",
    "id": 6,
    "summary": "2025年6月16日，先声再明 与 Nextcure 就 交易达成合作。交易标的为 CDH6（ADC、实体瘤）。项目当前处于 I期 阶段。首付款 未透露，潜在总交易额 7.5。合作地域覆盖 全球（不包括中国内地）。"
  },
  {
    "category": "肿瘤",
    "date": "2025年6月5日",
    "month": "2025-06",
    "product": "CD3×BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "indication": "多发性骨髓瘤",
    "stage": "II期",
    "stageNorm": "II期",
    "licenser": "智翔金泰",
    "licensee": "Cullinan",
    "upfront": "2000万",
    "upfrontType": "首付款",
    "totalValue": "16.9",
    "coop": "授权",
    "territory": "全球（不包括中国内地）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/6Q5c1ugE72Z85d8jUzSRQQ",
    "id": 7,
    "summary": "2025年6月5日，智翔金泰 与 Cullinan 就 授权达成合作。交易标的为 CD3×BCMA（TCE、多发性骨髓瘤）。项目当前处于 II期 阶段。首付款 2000万（首付款），潜在总交易额 16.9。合作地域覆盖 全球（不包括中国内地）。"
  },
  {
    "category": "肿瘤",
    "date": "2025年6月2日",
    "month": "2025-06",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "三阴性乳腺癌和小细胞肺癌",
    "stage": "III期",
    "stageNorm": "III期",
    "licenser": "BioNtech",
    "licensee": "BMS",
    "upfront": "15亿",
    "upfrontType": "首付款",
    "totalValue": "20",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/peWaO6AbNss4jsgUIFeEmQ",
    "id": 8,
    "summary": "2025年6月2日，BioNtech 与 BMS 就 授权达成合作。交易标的为 PD-L1/VEGF（双抗、三阴性乳腺癌和小细胞肺癌）。项目当前处于 III期 阶段。首付款 15亿（首付款），潜在总交易额 20。合作地域覆盖 全球。"
  },
  {
    "category": "自免",
    "date": "2025年6月26日",
    "month": "2025-06",
    "product": "IL11",
    "productType": "单抗",
    "diseaseType": "",
    "indication": "自免（年龄相关疾病）",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "迈威",
    "licensee": "Calico Life",
    "upfront": "2500万",
    "upfrontType": "首付款",
    "totalValue": "4.71",
    "coop": "授权",
    "territory": "全球（除大中华区外）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/-jGzUpzIDu489ba1wuMQ6Q",
    "id": 9,
    "summary": "2025年6月26日，迈威 与 Calico Life 就 授权达成合作。交易标的为 IL11（单抗、自免（年龄相关疾病））。项目当前处于 I期 阶段。首付款 2500万（首付款），潜在总交易额 4.71。合作地域覆盖 全球（除大中华区外）。"
  },
  {
    "category": "自免",
    "date": "2025年6月23日",
    "month": "2025-06",
    "product": "CD3×BCMA",
    "productType": "TCE",
    "diseaseType": "",
    "indication": "自免",
    "stage": "IND",
    "stageNorm": "IND",
    "licenser": "和铂",
    "licensee": "大塚制药",
    "upfront": "4700万",
    "upfrontType": "首付和近期里程碑",
    "totalValue": "7",
    "coop": "授权",
    "territory": "全球（除大中华区外）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/D56mwROLobkYa2ihY3Rr3g",
    "id": 10,
    "summary": "2025年6月23日，和铂 与 大塚制药 就 授权达成合作。交易标的为 CD3×BCMA（TCE、自免）。项目当前处于 IND 阶段。首付款 4700万（首付和近期里程碑），潜在总交易额 7。合作地域覆盖 全球（除大中华区外）。"
  },
  {
    "category": "代谢",
    "date": "2025年6月2日",
    "month": "2025-06",
    "product": "GLP-1/GIP",
    "productType": "",
    "diseaseType": "代谢",
    "indication": "",
    "stage": "中国III期",
    "stageNorm": "III期",
    "licenser": "翰森",
    "licensee": "再生元",
    "upfront": "8000万",
    "upfrontType": "首付款",
    "totalValue": "19.3",
    "coop": "授权",
    "territory": "全球独占许可（不含中国内地、香港及澳门）。",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/rkaiYETNNE7XHS94837BpQ",
    "id": 11,
    "summary": "2025年6月2日，翰森 与 再生元 就 授权达成合作。交易标的为 GLP-1/GIP。项目当前处于 中国III期 阶段。首付款 8000万（首付款），潜在总交易额 19.3。合作地域覆盖 全球独占许可（不含中国内地、香港及澳门）。。"
  },
  {
    "category": "肿瘤",
    "date": "2025年5月30日",
    "month": "2025-05",
    "product": "CLDN18.2",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "胃癌",
    "stage": "II期",
    "stageNorm": "II期",
    "licenser": "信诺威",
    "licensee": "安斯泰来",
    "upfront": "1.3亿",
    "upfrontType": "1.3亿美元的首付款，并有资格收取最高7000万美元的近期付款",
    "totalValue": "13.4",
    "coop": "授权",
    "territory": "全球（除中国大陆、香港、澳门和台湾地区外）",
    "notes": "用于 CLDN18.2 表达的局部晚期不可切除或转移性 HER2 阴性胃或胃食管结合部腺癌的三线及以上治疗",
    "source": "https://mp.weixin.qq.com/s/ai1aG32GEmBA2Hj1_5Ol4g",
    "id": 12,
    "summary": "2025年5月30日，信诺威 与 安斯泰来 就 授权达成合作。交易标的为 CLDN18.2（ADC、胃癌）。项目当前处于 II期 阶段。首付款 1.3亿（1.3亿美元的首付款，并有资格收取最高7000万美元的近期付款），潜在总交易额 13.4。合作地域覆盖 全球（除中国大陆、香港、澳门和台湾地区外）。用于 CLDN18.2 表达的局部晚期不可切除或转移性 HER2 阴性胃或胃食管结合部腺癌的三线及以上治疗"
  },
  {
    "category": "肿瘤",
    "date": "2025年5月20日",
    "month": "2025-05",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "非小细胞肺癌（NSCLC）",
    "stage": "II期",
    "stageNorm": "II期",
    "licenser": "三生制药",
    "licensee": "辉瑞",
    "upfront": "12.5亿",
    "upfrontType": "首付款",
    "totalValue": "48亿",
    "coop": "授权",
    "territory": "全球（不包括中国内地）",
    "notes": "",
    "source": "https://www.3sbio.com/news/details.aspx?id=307",
    "id": 13,
    "summary": "2025年5月20日，三生制药 与 辉瑞 就 授权达成合作。交易标的为 PD-1/VEGF（双抗、非小细胞肺癌（NSCLC））。项目当前处于 II期 阶段。首付款 12.5亿（首付款），潜在总交易额 48亿。合作地域覆盖 全球（不包括中国内地）。"
  },
  {
    "category": "代谢",
    "date": "2025年3月25日",
    "month": "2025-03",
    "product": "脂蛋白(a)[Lp(a)]",
    "productType": "小分子",
    "diseaseType": "代谢",
    "indication": "降脂",
    "stage": "2期",
    "stageNorm": "II期",
    "licenser": "恒瑞",
    "licensee": "MSD",
    "upfront": "2亿",
    "upfrontType": "首付款",
    "totalValue": "17.7",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/LPKi04Jk_7FnpckaTo8ZQA",
    "id": 14,
    "summary": "2025年3月25日，恒瑞 与 MSD 就 授权达成合作。交易标的为 脂蛋白(a)[Lp(a)]（小分子、降脂）。项目当前处于 2期 阶段。首付款 2亿（首付款），潜在总交易额 17.7。合作地域覆盖 大中华区以外。"
  },
  {
    "category": "代谢",
    "date": "2025年3月25日",
    "month": "2025-03",
    "product": "GLP-1、GIP和胰高血糖素受体三重激动剂",
    "productType": "",
    "diseaseType": "",
    "indication": "肥胖症、2型糖尿病",
    "stage": "1b期试验",
    "stageNorm": "其他",
    "licenser": "联邦制药",
    "licensee": "诺和诺德",
    "upfront": "2亿",
    "upfrontType": "首付款",
    "totalValue": "18",
    "coop": "授权",
    "territory": "全球（除中国大陆、香港、澳门和台湾地区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748881762&ver=6028&signature=3spJKOZBcsO3xB5dn5ySAd8HHtvXhpeIiMhw8VQ4XQC6sBdIBORj5Lh7fTNoFjXgn2269PhHADJvBAHFKU7LIFd2HbPFhESWp9yPfy*G4nAxw7*9Db6-3aOp-AHHlADh&new=1",
    "id": 15,
    "summary": "2025年3月25日，联邦制药 与 诺和诺德 就 授权达成合作。交易标的为 GLP-1、GIP和胰高血糖素受体三重激动剂（肥胖症、2型糖尿病）。项目当前处于 1b期试验 阶段。首付款 2亿（首付款），潜在总交易额 18。合作地域覆盖 全球（除中国大陆、香港、澳门和台湾地区）。"
  },
  {
    "category": "肿瘤",
    "date": "2025年2月19日",
    "month": "2025-02",
    "product": "ROR1",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "肿瘤",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "石药",
    "licensee": "Radiance\nBiopharma",
    "upfront": "1500万",
    "upfrontType": "首付款",
    "totalValue": "1.5+10.75",
    "coop": "授权",
    "territory": "其中开发里程碑款项累计不超过1.5亿美元，销售里程碑款项累计不超过10.75亿美元。",
    "notes": "在美国、欧盟、英国、瑞士、挪威、冰岛、列支敦士登、阿尔巴尼亚、黑山、北马其顿、塞尔维亚、澳大利亚和加拿大开发和商业化SYS6005的独家权利",
    "source": "https://mp.weixin.qq.com/s/10DlZe9K5KExvweZARpFuw",
    "id": 16,
    "summary": "2025年2月19日，石药 与 Radiance\nBiopharma 就 授权达成合作。交易标的为 ROR1（ADC、肿瘤）。首付款 1500万（首付款），潜在总交易额 1.5+10.75。合作地域覆盖 其中开发里程碑款项累计不超过1.5亿美元，销售里程碑款项累计不超过10.75亿美元。。在美国、欧盟、英国、瑞士、挪威、冰岛、列支敦士登、阿尔巴尼亚、黑山、北马其顿、塞尔维亚、澳大利亚和加拿大开发和商业化SYS6005的独家权利"
  },
  {
    "category": "肿瘤",
    "date": "2025年1月22日",
    "month": "2025-01",
    "product": "CDH17",
    "productType": "ADC",
    "diseaseType": "",
    "indication": "肿瘤",
    "stage": "pre-IND",
    "stageNorm": "IND",
    "licenser": "乐普生物",
    "licensee": "ArriVent Biopharma",
    "upfront": "4700万",
    "upfrontType": "首付和近期里程碑",
    "totalValue": "11.6",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://www.lepubiopharma.com/new/216.html",
    "id": 17,
    "summary": "2025年1月22日，乐普生物 与 ArriVent Biopharma 就 授权达成合作。交易标的为 CDH17（ADC、肿瘤）。项目当前处于 pre-IND 阶段。首付款 4700万（首付和近期里程碑），潜在总交易额 11.6。合作地域覆盖 大中华区以外。"
  },
  {
    "category": "肿瘤",
    "date": "2025年1月13日",
    "month": "2025-01",
    "product": "SIM0500(GPRC5D-BCMA-CD3)",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "多发性骨髓瘤",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "先声再明",
    "licensee": "Abbvie",
    "upfront": "未公布",
    "upfrontType": "",
    "totalValue": "10.55",
    "coop": "授权",
    "territory": "大中华地区",
    "notes": "",
    "source": "https://www.simcere.com/news/detail.aspx?mtt=1485",
    "id": 18,
    "summary": "2025年1月13日，先声再明 与 Abbvie 就 授权达成合作。交易标的为 SIM0500(GPRC5D-BCMA-CD3)（TCE、多发性骨髓瘤）。项目当前处于 I期 阶段。首付款 未公布，潜在总交易额 10.55。合作地域覆盖 大中华地区。"
  },
  {
    "category": "肿瘤",
    "date": "2025年1月8日",
    "month": "2025-01",
    "product": "EGFR/HER3",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "IND",
    "stageNorm": "IND",
    "licenser": "映恩",
    "licensee": "Avenzo",
    "upfront": "5000万",
    "upfrontType": "首付款",
    "totalValue": "11.5",
    "coop": "授权",
    "territory": "全球（除大中华区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/dwruRrwz4bLVfF_lOli-Dg",
    "id": 19,
    "summary": "2025年1月8日，映恩 与 Avenzo 就 授权达成合作。交易标的为 EGFR/HER3（双抗ADC）。项目当前处于 IND 阶段。首付款 5000万（首付款），潜在总交易额 11.5。合作地域覆盖 全球（除大中华区）。"
  },
  {
    "category": "肿瘤",
    "date": "2025年1月2日",
    "month": "2025-01",
    "product": "DLL3",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "SCLC",
    "stage": "临床I期",
    "stageNorm": "其他",
    "licenser": "信达",
    "licensee": "罗氏",
    "upfront": "8000万",
    "upfrontType": "首付款",
    "totalValue": "10",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/jEdc_W_Pqkcl9erIdk-kFQ",
    "id": 20,
    "summary": "2025年1月2日，信达 与 罗氏 就 授权达成合作。交易标的为 DLL3（ADC、SCLC）。项目当前处于 临床I期 阶段。首付款 8000万（首付款），潜在总交易额 10。合作地域覆盖 全球。"
  },
  {
    "category": "肿瘤",
    "date": "2024年12月29日",
    "month": "2024-12",
    "product": "DLL3",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "临床I期",
    "stageNorm": "其他",
    "licenser": "恒瑞",
    "licensee": "IDEAYA",
    "upfront": "7500万",
    "upfrontType": "首付款",
    "totalValue": "2",
    "coop": "授权",
    "territory": "全球（除大中华区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/KaqNt4gtAiYcA0LKl24_sw",
    "id": 21,
    "summary": "2024年12月29日，恒瑞 与 IDEAYA 就 授权达成合作。交易标的为 DLL3（ADC）。项目当前处于 临床I期 阶段。首付款 7500万（首付款），潜在总交易额 2。合作地域覆盖 全球（除大中华区）。"
  },
  {
    "category": "肿瘤",
    "date": "2024年12月4日",
    "month": "2024-12",
    "product": "DB-1324\nADAM9/CDH17?",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "映恩生物",
    "licensee": "GSK",
    "upfront": "3000万",
    "upfrontType": "预付款及其他行权前里程碑付款",
    "totalValue": "9.75亿",
    "coop": "授权",
    "territory": "全球范围内（中国大陆、香港地区和澳门地区除外）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1733303268&ver=5668&signature=bHt7tKfzKB5kSTn3cy4Cnmmyzk1bv*6ew8Hcgu5E8jwbKnnUdqXp6urtvPwcXOpOIq-UCU0eBHbOBFPvI6*DRLV6-7ZlfGdA6HMoI4jmq3SHEorrXYQTcK2fPYCKWym5&new=1",
    "id": 22,
    "summary": "2024年12月4日，映恩生物 与 GSK 就 授权达成合作。交易标的为 DB-1324\nADAM9/CDH17?（ADC、肿瘤）。项目当前处于 临床前 阶段。首付款 3000万（预付款及其他行权前里程碑付款），潜在总交易额 9.75亿。合作地域覆盖 全球范围内（中国大陆、香港地区和澳门地区除外）。"
  },
  {
    "category": "代谢",
    "date": "2024年12月18日",
    "month": "2024-12",
    "product": "GLP-1",
    "productType": "小分子",
    "diseaseType": "代谢",
    "indication": "",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "翰森",
    "licensee": "默沙东",
    "upfront": "1.12亿",
    "upfrontType": "首付款",
    "totalValue": "18",
    "coop": "授权",
    "territory": "全球（在特定条件下，翰森制药可能会在中国共同推广或独家商业化）",
    "notes": "口服小分子",
    "source": "https://www.merck.com/news/merck-enters-into-exclusive-global-license-agreement-with-hansoh-pharma-for-investigational-oral-glp-1-receptor-agonist/",
    "id": 23,
    "summary": "2024年12月18日，翰森 与 默沙东 就 授权达成合作。交易标的为 GLP-1（小分子）。项目当前处于 临床前 阶段。首付款 1.12亿（首付款），潜在总交易额 18。合作地域覆盖 全球（在特定条件下，翰森制药可能会在中国共同推广或独家商业化）。口服小分子"
  },
  {
    "category": "肿瘤",
    "date": "2024年11月18日",
    "month": "2024-11",
    "product": "TROP2/NECTIN4",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "橙帆医药",
    "licensee": "Avenzo",
    "upfront": "5000万",
    "upfrontType": "首付款及近期里程碑付款",
    "totalValue": "7.5",
    "coop": "授权",
    "territory": "全球范围（不包括大中华区）",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s/XjkYoCEeG7k1r6pNerZMlw https://mp.weixin.qq.com/s/tP7di-D-VS_2NwatpbE4ww\nhttps://mp.weixin.qq.com/s?src=11&timestamp=1733492444&ver=5672&signature=26M3E7w6a8KE0wBWvsSoAXc1tHjwtg7MFJgh-buFxcco8CAS29622cZB8H5q*wNTV2q2Gxlyj7qL*ItfRDEmP9HPIW5XIQCp4ZteynYjhSv1eRcS8T8F3d7L*F2ITfM1&new=1",
    "id": 24,
    "summary": "2024年11月18日，橙帆医药 与 Avenzo 就 授权达成合作。交易标的为 TROP2/NECTIN4（双抗ADC、肿瘤）。项目当前处于 临床前 阶段。首付款 5000万（首付款及近期里程碑付款），潜在总交易额 7.5。合作地域覆盖 全球范围（不包括大中华区）。"
  },
  {
    "category": "肿瘤",
    "date": "2024年11月17日",
    "month": "2024-11",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "療復發或難治性多發性骨髓瘤",
    "stage": "I/II期",
    "stageNorm": "II期",
    "licenser": "康诺亚",
    "licensee": "Platina Medicines Ltd",
    "upfront": "1600万",
    "upfrontType": "首付款和\n近期付款",
    "totalValue": "6.1",
    "coop": "NewCo",
    "territory": "全球（不包括中國內\n地、香港、澳門及台灣）",
    "notes": "",
    "source": "https://staticpacific.blob.core.windows.net/press-releases-attachments/3504798/HKEX-EPS_20241117_11442884_0.PDF",
    "id": 25,
    "summary": "2024年11月17日，康诺亚 与 Platina Medicines Ltd 就 NewCo达成合作。交易标的为 CD3/BCMA（TCE、療復發或難治性多發性骨髓瘤）。项目当前处于 I/II期 阶段。首付款 1600万（首付款和\n近期付款），潜在总交易额 6.1。合作地域覆盖 全球（不包括中國內\n地、香港、澳門及台灣）。"
  },
  {
    "category": "肿瘤",
    "date": "2024年11月14日",
    "month": "2024-11",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "I期招募中",
    "stageNorm": "其他",
    "licenser": "礼新",
    "licensee": "默沙东",
    "upfront": "5.88亿",
    "upfrontType": "首付款",
    "totalValue": "27",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://www.msdchina.com.cn/2024/11/14/company_news_2024-11-14/",
    "id": 26,
    "summary": "2024年11月14日，礼新 与 默沙东 就 授权达成合作。交易标的为 PD-1/VEGF（双抗、肿瘤）。项目当前处于 I期招募中 阶段。首付款 5.88亿（首付款），潜在总交易额 27。合作地域覆盖 全球。"
  },
  {
    "category": "肿瘤",
    "date": "2024年11月13日",
    "month": "2024-11",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "三阴性乳腺癌和小细胞肺癌",
    "stage": "III期",
    "stageNorm": "III期",
    "licenser": "普米斯",
    "licensee": "BioNTech SE",
    "upfront": "8亿",
    "upfrontType": "100%已发行股本",
    "totalValue": "",
    "coop": "收购",
    "territory": "",
    "notes": "1、已有700多名患者接受了临床试验/2、和映恩的TROP2-ADC在做联用；3、南通生产基地；4、300多名员工",
    "source": "https://www.sec.gov/Archives/edgar/data/1776985/000177698524000094/a99_1biontechtoacquirebiot.htmhttps://cn.biotheus.com/news/344.html",
    "id": 27,
    "summary": "2024年11月13日，普米斯 与 BioNTech SE 就 收购达成合作。交易标的为 PD-L1/VEGF（双抗、三阴性乳腺癌和小细胞肺癌）。项目当前处于 III期 阶段。首付款 8亿（100%已发行股本）。1、已有700多名患者接受了临床试验/2、和映恩的TROP2-ADC在做联用；3、南通生产基地；4、300多名员工"
  },
  {
    "category": "自免",
    "date": "2024年11月18日",
    "month": "2024-11",
    "product": "TSLP、TSLP/IL-4R",
    "productType": "双抗",
    "diseaseType": "自免",
    "indication": "重度特应性皮炎；重症哮喘和慢性鼻窦炎伴鼻息肉",
    "stage": "TSLP美国2a中国2期, 双抗临床前",
    "stageNorm": "II期",
    "licenser": "博奥信",
    "licensee": "Aclaris Therapeutics",
    "upfront": "3000万",
    "upfrontType": "首付款以及承担部分开发成本和药物产品材料费用",
    "totalValue": "9",
    "coop": "NewCo",
    "territory": "全球（除大中华区外）",
    "notes": "",
    "source": "https://www.sec.gov/ix?doc=/Archives/edgar/data/1557746/000155837024015838/acrs-20241116x8k.htm  https://cn.biosion.com/news/datail/673b423b804acf5a200b92a8",
    "id": 28,
    "summary": "2024年11月18日，博奥信 与 Aclaris Therapeutics 就 NewCo达成合作。交易标的为 TSLP、TSLP/IL-4R（双抗、重度特应性皮炎；重症哮喘和慢性鼻窦炎伴鼻息肉）。项目当前处于 TSLP美国2a中国2期, 双抗临床前 阶段。首付款 3000万（首付款以及承担部分开发成本和药物产品材料费用），潜在总交易额 9。合作地域覆盖 全球（除大中华区外）。"
  },
  {
    "category": "自免",
    "date": "2024年11月7日",
    "month": "2024-11",
    "product": "CD3/BCMA/CD19",
    "productType": "TCE",
    "diseaseType": "自免",
    "indication": "自免",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "维立志博",
    "licensee": "Oblenio",
    "upfront": "3500万",
    "upfrontType": "首付款和近期付款",
    "totalValue": "5.79",
    "coop": "NewCo",
    "territory": "",
    "notes": "",
    "source": "https://www.leadsbiolabs.com/id45497156.html",
    "id": 29,
    "summary": "2024年11月7日，维立志博 与 Oblenio 就 NewCo达成合作。交易标的为 CD3/BCMA/CD19（TCE、自免）。项目当前处于 临床前 阶段。首付款 3500万（首付款和近期付款），潜在总交易额 5.79。"
  },
  {
    "category": "自免",
    "date": "2024年10月29日",
    "month": "2024-10",
    "product": "CD3/CD19/CD20",
    "productType": "TCE",
    "diseaseType": "自免",
    "indication": "系统性红斑狼疮（SLE）和狼疮性肾炎（LN）",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "恩沐生物",
    "licensee": "GSK",
    "upfront": "3亿",
    "upfrontType": "首付款",
    "totalValue": "5.5",
    "coop": "授权",
    "territory": "",
    "notes": "",
    "source": "https://news.bioon.com/article/f564850019c9.html",
    "id": 30,
    "summary": "2024年10月29日，恩沐生物 与 GSK 就 授权达成合作。交易标的为 CD3/CD19/CD20（TCE、系统性红斑狼疮（SLE）和狼疮性肾炎（LN））。项目当前处于 I期 阶段。首付款 3亿（首付款），潜在总交易额 5.5。"
  },
  {
    "category": "代谢",
    "date": "2024年10月8日",
    "month": "2024-10",
    "product": "脂蛋白(a)[Lp(a)]",
    "productType": "小分子",
    "diseaseType": "代谢",
    "indication": "降脂",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "石药",
    "licensee": "AZ",
    "upfront": "1亿",
    "upfrontType": "首付款",
    "totalValue": "19.2",
    "coop": "转让",
    "territory": "全球权益",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748881171&ver=6028&signature=ktmXthAkzOm8nj3lrGbeY4-gKDUjW8*Nd5ykHRxaqyamuwvTu9hJF8GQYo-fht6y*Bf7qVMW0SpO10BnGfXn0NYhXPxn*uYf9o70HwydUR9m0YBcAMY1UTbUCQECkTG*&new=1",
    "id": 31,
    "summary": "2024年10月8日，石药 与 AZ 就 转让达成合作。交易标的为 脂蛋白(a)[Lp(a)]（小分子、降脂）。项目当前处于 临床前 阶段。首付款 1亿（首付款），潜在总交易额 19.2。合作地域覆盖 全球权益。"
  },
  {
    "category": "肿瘤",
    "date": "2024年9月4日",
    "month": "2024-09",
    "product": "CD3/BCMA",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "多发性骨髓瘤",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "岸迈生物",
    "licensee": "Vignette",
    "upfront": "6000万",
    "upfrontType": "现金和Vignette股权",
    "totalValue": "5.75",
    "coop": "NewCo",
    "territory": "大中华区（包括中国大陆，香港，澳门和台湾地区）以外",
    "notes": "",
    "source": "https://www.epimab.com/cn/news/41",
    "id": 32,
    "summary": "2024年9月4日，岸迈生物 与 Vignette 就 NewCo达成合作。交易标的为 CD3/BCMA（TCE、多发性骨髓瘤）。项目当前处于 I期 阶段。首付款 6000万（现金和Vignette股权），潜在总交易额 5.75。合作地域覆盖 大中华区（包括中国大陆，香港，澳门和台湾地区）以外。"
  },
  {
    "category": "肿瘤",
    "date": "2024年8月30日",
    "month": "2024-08",
    "product": "KRAS G12C抑制剂戈来雷塞和SHP2抑制剂JAB-3312",
    "productType": "小分子",
    "diseaseType": "肿瘤",
    "indication": "KRAS G12C突变的晚期或转移性非小细胞肺癌患者",
    "stage": "III期",
    "stageNorm": "III期",
    "licenser": "加科思",
    "licensee": "艾力斯",
    "upfront": "1.5亿RMB",
    "upfrontType": "首付款",
    "totalValue": "7",
    "coop": "授权",
    "territory": "中国（包括中国大陆、香港、澳门和台湾地区）",
    "notes": "",
    "source": "https://www.allist.com.cn/newsd/101/2086.html",
    "id": 33,
    "summary": "2024年8月30日，加科思 与 艾力斯 就 授权达成合作。交易标的为 KRAS G12C抑制剂戈来雷塞和SHP2抑制剂JAB-3312（小分子、KRAS G12C突变的晚期或转移性非小细胞肺癌患者）。项目当前处于 III期 阶段。首付款 1.5亿RMB（首付款），潜在总交易额 7。合作地域覆盖 中国（包括中国大陆、香港、澳门和台湾地区）。"
  },
  {
    "category": "肿瘤",
    "date": "2024年8月19日",
    "month": "2024-08",
    "product": "未披露",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "肺癌、消化道肿瘤等多种实体瘤",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "科伦博泰",
    "licensee": "默沙东",
    "upfront": "3750万",
    "upfrontType": "",
    "totalValue": "未披露",
    "coop": "授权",
    "territory": "未披露",
    "notes": "",
    "source": "",
    "id": 34,
    "summary": "2024年8月19日，科伦博泰 与 默沙东 就 授权达成合作。交易标的为 未披露（双抗ADC、肺癌、消化道肿瘤等多种实体瘤）。项目当前处于 临床前 阶段。首付款 3750万，潜在总交易额 未披露。合作地域覆盖 未披露。"
  },
  {
    "category": "肿瘤",
    "date": "2024年8月9日",
    "month": "2024-08",
    "product": "CD3/CD19",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "B细胞肿瘤",
    "stage": "1期和1b/2期",
    "stageNorm": "II期",
    "licenser": "同润生物",
    "licensee": "默沙东",
    "upfront": "7亿",
    "upfrontType": "首付款",
    "totalValue": "6",
    "coop": "转让",
    "territory": "全球",
    "notes": "",
    "source": "https://www.msdchina.com.cn/2024/08/09/company_news/",
    "id": 35,
    "summary": "2024年8月9日，同润生物 与 默沙东 就 转让达成合作。交易标的为 CD3/CD19（TCE、B细胞肿瘤）。项目当前处于 1期和1b/2期 阶段。首付款 7亿（首付款），潜在总交易额 6。合作地域覆盖 全球。"
  },
  {
    "category": "肿瘤",
    "date": "2024年8月5日",
    "month": "2024-08",
    "product": "CD3/CD20",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "嘉和生物",
    "licensee": "TRC2004",
    "upfront": "数千万",
    "upfrontType": "首付款",
    "totalValue": "4.43",
    "coop": "NewCo",
    "territory": "全球独家许可（不包括中国大陆、香港、澳门及台湾）",
    "notes": "TRC 2004被许可人数量可观的股权",
    "source": "https://www.genorbio.com/cn/media/corporate-news/20240805/",
    "id": 36,
    "summary": "2024年8月5日，嘉和生物 与 TRC2004 就 NewCo达成合作。交易标的为 CD3/CD20（TCE、肿瘤）。项目当前处于 I期 阶段。首付款 数千万（首付款），潜在总交易额 4.43。合作地域覆盖 全球独家许可（不包括中国大陆、香港、澳门及台湾）。TRC 2004被许可人数量可观的股权"
  },
  {
    "category": "肿瘤",
    "date": "2024年8月1日",
    "month": "2024-08",
    "product": "PD-L1/VEGF和CTLA-4",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "三阴性乳腺癌和非小细胞肺癌",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "宜明昂科",
    "licensee": "SynBioTx (Instil Bio)",
    "upfront": "1,000万",
    "upfrontType": "首付款",
    "totalValue": "20",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://www.sec.gov/Archives/edgar/data/1789769/000178976924000077/til-20240801.htm  http://www.immuneonco.com/news/gsdynamics/583.html",
    "id": 37,
    "summary": "2024年8月1日，宜明昂科 与 SynBioTx (Instil Bio) 就 授权达成合作。交易标的为 PD-L1/VEGF和CTLA-4（双抗、三阴性乳腺癌和非小细胞肺癌）。项目当前处于 I期 阶段。首付款 1,000万（首付款），潜在总交易额 20。合作地域覆盖 大中华区以外。"
  },
  {
    "category": "自免",
    "date": "2024年7月9日",
    "month": "2024-07",
    "product": "2款自免双抗 CM512（推测IL13/TSLP）及CM536",
    "productType": "双抗",
    "diseaseType": "自免",
    "indication": "自免",
    "stage": "未知",
    "stageNorm": "其他",
    "licenser": "康诺亚",
    "licensee": "Belenos",
    "upfront": "1500万",
    "upfrontType": "首付款和近期付款",
    "totalValue": "1.75",
    "coop": "NewCo",
    "territory": "全球（不包括大中華地區）",
    "notes": "",
    "source": "https://staticpacific.blob.core.windows.net/press-releases-attachments/2903339/HKEX-EPS_20240709_11280365_0.PDF",
    "id": 38,
    "summary": "2024年7月9日，康诺亚 与 Belenos 就 NewCo达成合作。交易标的为 2款自免双抗 CM512（推测IL13/TSLP）及CM536（双抗、自免）。项目当前处于 未知 阶段。首付款 1500万（首付款和近期付款），潜在总交易额 1.75。合作地域覆盖 全球（不包括大中華地區）。"
  },
  {
    "category": "肿瘤",
    "date": "2024年6月18日",
    "month": "2024-06",
    "product": "PTK7",
    "productType": "ADC",
    "diseaseType": "肿瘤",
    "indication": "",
    "stage": "IND",
    "stageNorm": "IND",
    "licenser": "麦科思/普众",
    "licensee": "Day One",
    "upfront": "5500 万",
    "upfrontType": "首付款",
    "totalValue": "11.52",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://news.qq.com/rain/a/20240619A06J5O00",
    "id": 39,
    "summary": "2024年6月18日，麦科思/普众 与 Day One 就 授权达成合作。交易标的为 PTK7（ADC）。项目当前处于 IND 阶段。首付款 5500 万（首付款），潜在总交易额 11.52。合作地域覆盖 大中华区以外。"
  },
  {
    "category": "自免",
    "date": "2024年1月9日",
    "month": "2024-01",
    "product": "TSLP",
    "productType": "单抗",
    "diseaseType": "自免",
    "indication": "中重度哮喘",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "Aiolos",
    "licensee": "GSK",
    "upfront": "10亿",
    "upfrontType": "预付款",
    "totalValue": "4",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "Aiolos公司表示，阻断TSLP是唯一能对所有类型的中重度哮喘产生临床疗效的生物方法。",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748878345&ver=6028&signature=GNSEYRREDK4ToIYhDX2oTmM7heQz6HQorz9HbMKp4A8*znj5alARrNdnSIHinnMbdq5QgsRpgA18-f7Mqb5Afp0Fkx6wa5SMl1FSclU6fZ6DJYd0WhMmLf4TNzAw-Iun&new=1",
    "id": 40,
    "summary": "2024年1月9日，Aiolos 与 GSK 就 授权达成合作。交易标的为 TSLP（单抗、中重度哮喘）。首付款 10亿（预付款），潜在总交易额 4。合作地域覆盖 大中华区以外。Aiolos公司表示，阻断TSLP是唯一能对所有类型的中重度哮喘产生临床疗效的生物方法。"
  },
  {
    "category": "肿瘤",
    "date": "2023年12月28日",
    "month": "2023-12",
    "product": "PD-L1/SIRPα",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "科望医药",
    "licensee": "安斯泰来",
    "upfront": "3700万",
    "upfrontType": "首付款和行权费",
    "totalValue": "17",
    "coop": "合作开发及授权",
    "territory": "",
    "notes": "另一分子未公开",
    "source": "https://www.astellas.com/en/news/28816",
    "id": 41,
    "summary": "2023年12月28日，科望医药 与 安斯泰来 就 合作开发及授权达成合作。交易标的为 PD-L1/SIRPα（双抗、肿瘤）。项目当前处于 临床前 阶段。首付款 3700万（首付款和行权费），潜在总交易额 17。另一分子未公开"
  },
  {
    "category": "肿瘤",
    "date": "2023年12月12日",
    "month": "2023-12",
    "product": "EGFR/HER3",
    "productType": "双抗ADC",
    "diseaseType": "肿瘤",
    "indication": "在转移性或不可切除的非小细胞肺癌（NSCLC）",
    "stage": "I期",
    "stageNorm": "其他",
    "licenser": "百利天恒",
    "licensee": "BMS",
    "upfront": "8亿",
    "upfrontType": "首付款",
    "totalValue": "84",
    "coop": "授权",
    "territory": "中国大陆以外",
    "notes": "SystImmune 将通过其关联公司独家负责 BL-B01D1 在中国大陆的开发、商业化以及在中国大陆的生产，并负责生产部分供中国大陆以外地区使用的药品。BMS 将独家负责 BL-B01D1 在全球其他地区的开发和商业化。",
    "source": "http://www.baili-pharm.com/upload/2023-12-12/128238727.pdf",
    "id": 42,
    "summary": "2023年12月12日，百利天恒 与 BMS 就 授权达成合作。交易标的为 EGFR/HER3（双抗ADC、在转移性或不可切除的非小细胞肺癌（NSCLC））。项目当前处于 I期 阶段。首付款 8亿（首付款），潜在总交易额 84。合作地域覆盖 中国大陆以外。SystImmune 将通过其关联公司独家负责 BL-B01D1 在中国大陆的开发、商业化以及在中国大陆的生产，并负责生产部分供中国大陆以外地区使用的药品。BMS 将独家负责 BL-B01D1 在全球其他地区的开发和商业化。"
  },
  {
    "category": "肿瘤",
    "date": "2023年11月6日",
    "month": "2023-11",
    "product": "PD-L1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "实体瘤",
    "stage": "中国II期",
    "stageNorm": "II期",
    "licenser": "普米斯",
    "licensee": "BioNTech SE",
    "upfront": "5500万",
    "upfrontType": "首付款",
    "totalValue": "10",
    "coop": "授权",
    "territory": "全球（大中华区除外）",
    "notes": "",
    "source": "https://cn.biotheus.com/news/333.html",
    "id": 43,
    "summary": "2023年11月6日，普米斯 与 BioNTech SE 就 授权达成合作。交易标的为 PD-L1/VEGF（双抗、实体瘤）。项目当前处于 中国II期 阶段。首付款 5500万（首付款），潜在总交易额 10。合作地域覆盖 全球（大中华区除外）。"
  },
  {
    "category": "自免",
    "date": "2023年8月14日",
    "month": "2023-08",
    "product": "TSLP",
    "productType": "单抗",
    "diseaseType": "自免",
    "indication": "中重度哮喘",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "恒瑞",
    "licensee": "One Bio",
    "upfront": "2150",
    "upfrontType": "首付款",
    "totalValue": "10.25",
    "coop": "授权",
    "territory": "大中华区以外",
    "notes": "",
    "source": "https://mp.weixin.qq.com/s?src=11&timestamp=1748878236&ver=6028&signature=CIKsE1y98PV20svBZmapYRBV49Mo-bBOTpcu-yOFh-*WVapY5HKGjpTzmR9SR9PUpCzX*0I7G-lpkvcwhcmbgFxO9usGyzfzDabeQz*udoP-VCSIugV5OD6TB5zArXc5&new=1",
    "id": 44,
    "summary": "2023年8月14日，恒瑞 与 One Bio 就 授权达成合作。交易标的为 TSLP（单抗、中重度哮喘）。首付款 2150（首付款），潜在总交易额 10.25。合作地域覆盖 大中华区以外。"
  },
  {
    "category": "肿瘤",
    "date": "2023年1月5日",
    "month": "2023-01",
    "product": "4款TCE双抗",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "药明生物",
    "licensee": "GSK",
    "upfront": "4000万",
    "upfrontType": "首付款",
    "totalValue": "14.6",
    "coop": "授权",
    "territory": "全球",
    "notes": "",
    "source": "https://www.wuxibiologics.com.cn/wuxi-biologics-and-gsk-enter-into-license-agreement-on-multiple-novel-bi-multi-specific-t-cell-engagers/",
    "id": 45,
    "summary": "2023年1月5日，药明生物 与 GSK 就 授权达成合作。交易标的为 4款TCE双抗（TCE、肿瘤）。项目当前处于 临床前 阶段。首付款 4000万（首付款），潜在总交易额 14.6。合作地域覆盖 全球。"
  },
  {
    "category": "肿瘤",
    "date": "2022年12月6日",
    "month": "2022-12",
    "product": "PD-1/VEGF",
    "productType": "双抗",
    "diseaseType": "肿瘤",
    "indication": "非小细胞肺癌",
    "stage": "III期",
    "stageNorm": "III期",
    "licenser": "康方生物",
    "licensee": "Summit Therapeutics",
    "upfront": "5亿",
    "upfrontType": "首付款",
    "totalValue": "50亿",
    "coop": "授权",
    "territory": "美国、加拿大、欧洲和日本",
    "notes": "",
    "source": "https://www.akesobio.com/cn/media/akeso-news/20221206/",
    "id": 46,
    "summary": "2022年12月6日，康方生物 与 Summit Therapeutics 就 授权达成合作。交易标的为 PD-1/VEGF（双抗、非小细胞肺癌）。项目当前处于 III期 阶段。首付款 5亿（首付款），潜在总交易额 50亿。合作地域覆盖 美国、加拿大、欧洲和日本。"
  },
  {
    "category": "肿瘤",
    "date": "2022年4月7日",
    "month": "2022-04",
    "product": "CD3/CLDN18.2",
    "productType": "TCE",
    "diseaseType": "肿瘤",
    "indication": "肿瘤",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "和铂医药",
    "licensee": "阿斯利康",
    "upfront": "2500万",
    "upfrontType": "预付款",
    "totalValue": "3.25",
    "coop": "转让",
    "territory": "全球",
    "notes": "",
    "source": "https://www.harbourbiomed.cn/news/264.html",
    "id": 47,
    "summary": "2022年4月7日，和铂医药 与 阿斯利康 就 转让达成合作。交易标的为 CD3/CLDN18.2（TCE、肿瘤）。项目当前处于 临床前 阶段。首付款 2500万（预付款），潜在总交易额 3.25。合作地域覆盖 全球。"
  },
  {
    "category": "肿瘤",
    "date": "2021年7月1日",
    "month": "2021-07",
    "product": "甲磺酸伏美替尼",
    "productType": "小分子",
    "diseaseType": "肿瘤",
    "indication": "目前已获批用于EGFR突变非小细胞肺癌患者的二线治疗，具有“双活性、高选择、强缩瘤、安全佳”的特点。",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "艾力斯",
    "licensee": "ArriVent Biopharma",
    "upfront": "4000万",
    "upfrontType": "首付款",
    "totalValue": "7.65",
    "coop": "NewCo",
    "territory": "除中国大陆、中国台湾、中国香港和中国澳门外",
    "notes": "",
    "source": "",
    "id": 48,
    "summary": "2021年7月1日，艾力斯 与 ArriVent Biopharma 就 NewCo达成合作。交易标的为 甲磺酸伏美替尼（小分子、目前已获批用于EGFR突变非小细胞肺癌患者的二线治疗，具有“双活性、高选择、强缩瘤、安全佳”的特点。）。首付款 4000万（首付款），潜在总交易额 7.65。合作地域覆盖 除中国大陆、中国台湾、中国香港和中国澳门外。"
  },
  {
    "category": "自免",
    "date": "2021年3月1日",
    "month": "2021-03",
    "product": "TYK2抑制剂",
    "productType": "小分子",
    "diseaseType": "自免",
    "indication": "中度至重度斑块状银屑病、SLE",
    "stage": "临床前",
    "stageNorm": "临床前",
    "licenser": "海思科",
    "licensee": "Alumis",
    "upfront": "6000万",
    "upfrontType": "首付款",
    "totalValue": "1.2",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "https://xueqiu.com/4797094524/293423712",
    "id": 49,
    "summary": "2021年3月1日，海思科 与 Alumis 就 交易达成合作。交易标的为 TYK2抑制剂（小分子、中度至重度斑块状银屑病、SLE）。项目当前处于 临床前 阶段。首付款 6000万（首付款），潜在总交易额 1.2。"
  },
  {
    "category": "代谢",
    "date": "HS-20094",
    "month": "2009",
    "product": "（GLP-1/GIP双激动剂）虽是临床III期项目，但面临礼来替尔泊肽（Tirzepatide）的垄断压力，礼来凭借替尔泊肽已占据全球双靶点市场90%以上份额",
    "productType": "皮下注射液，不是口服",
    "diseaseType": "",
    "indication": "",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "",
    "licensee": "",
    "upfront": "",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "",
    "id": 50,
    "summary": "HS-20094，一笔 交易交易完成。交易标的为 （GLP-1/GIP双激动剂）虽是临床III期项目，但面临礼来替尔泊肽（Tirzepatide）的垄断压力，礼来凭借替尔泊肽已占据全球双靶点市场90%以上份额（皮下注射液，不是口服）。"
  },
  {
    "category": "代谢",
    "date": "减重、降糖",
    "month": "",
    "product": "体重管理、II型糖尿病",
    "productType": "",
    "diseaseType": "",
    "indication": "",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "",
    "licensee": "",
    "upfront": "",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "",
    "id": 51,
    "summary": "减重、降糖，一笔 交易交易完成。交易标的为 体重管理、II型糖尿病。"
  },
  {
    "category": "代谢",
    "date": "司美格鲁肽",
    "month": "",
    "product": "单一GLP-1受体激动剂，皮下",
    "productType": "",
    "diseaseType": "",
    "indication": "",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "",
    "licensee": "",
    "upfront": "",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "",
    "id": 52,
    "summary": "司美格鲁肽，一笔 交易交易完成。交易标的为 单一GLP-1受体激动剂，皮下。"
  },
  {
    "category": "代谢",
    "date": "替尔泊肽（Tirzepatide）",
    "month": "",
    "product": "单分子多肽，皮下注射，由礼来公司研发，作为全球首个且目前唯一的葡萄糖依赖性促胰岛素多肽（GIP）和胰高糖素样肽-1（GLP-1）双受体激动剂，主要用于治疗2型糖尿病和肥胖症。其核心特点包括强效降糖、显著减重及多重代谢获益。",
    "productType": "",
    "diseaseType": "",
    "indication": "",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "",
    "licensee": "",
    "upfront": "",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "",
    "id": 53,
    "summary": "替尔泊肽（Tirzepatide），一笔 交易交易完成。交易标的为 单分子多肽，皮下注射，由礼来公司研发，作为全球首个且目前唯一的葡萄糖依赖性促胰岛素多肽（GIP）和胰高糖素样肽-1（GLP-1）双受体激动剂，主要用于治疗2型糖尿病和肥胖症。其核心特点包括强效降糖、显著减重及多重代谢获益。。"
  },
  {
    "category": "代谢",
    "date": "GLP-1",
    "month": "",
    "product": "40%的体重减轻源自于肌肉含量的降低",
    "productType": "",
    "diseaseType": "",
    "indication": "",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "",
    "licensee": "",
    "upfront": "",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "",
    "id": 54,
    "summary": "GLP-1，一笔 交易交易完成。交易标的为 40%的体重减轻源自于肌肉含量的降低。"
  },
  {
    "category": "代谢",
    "date": "ACVR2A或2B",
    "month": "",
    "product": "激活素，要开发抑制剂，减脂增肌",
    "productType": "Bimagrumab（下称：Bima）和来凯医药LAE102",
    "diseaseType": "",
    "indication": "",
    "stage": "",
    "stageNorm": "其他",
    "licenser": "",
    "licensee": "",
    "upfront": "",
    "upfrontType": "",
    "totalValue": "",
    "coop": "",
    "territory": "",
    "notes": "",
    "source": "",
    "id": 55,
    "summary": "ACVR2A或2B，一笔 交易交易完成。交易标的为 激活素，要开发抑制剂，减脂增肌（Bimagrumab（下称：Bima）和来凯医药LAE102）。"
  }
];
